#! /bin/sh
# vim: ts=4 filetype=python expandtab shiftwidth=4 softtabstop=4 syntax=python
# pylint: disable-next=anomalous-backslash-in-string
''''eval version=$( ls /usr/bin/python3.* | \
    grep '.*[0-9]$' | sort -nr -k2 -t. | head -n1 ) && \
    version=${version##/usr/bin/python3.} && [ ${version} ] && \
    [ ${version} -ge 8 ] && exec /usr/bin/python3.${version} "$0" "$@" || \
    exec /usr/bin/env python3 "$0" "$@"' #'''
# The above hack is to handle distros where /usr/bin/python3
# doesn't point to the latest version of python3 they provide
# Requires: python3 (>= 3.8)
#
# Copyright the Cluster Management Toolkit for Kubernetes contributors.
# SPDX-License-Identifier: MIT

import errno
from pathlib import PurePath
import sys
from typing import Dict, List, Tuple
from unittest import mock
import yaml

from cmtio import secure_read_string, secure_write_string
from cmtpaths import DEFAULT_THEME_FILE
from cmttypes import deep_get, DictPath, FilePath, FilePathAuditError, SecurityStatus
from ansithemeprint import ANSIThemeStr, ansithemeprint, init_ansithemeprint
import commandparser

TEST_DIR = FilePath(PurePath(__file__).parent).joinpath("testpaths")

# unit-tests for commandparser.py


def yaml_dump(data: Dict, base_indent: int = 4) -> str:
    result = ""
    dump = yaml.dump(data)
    for line in dump.splitlines():
        result += f"{' '.ljust(base_indent)}{line}\n"
    return result


def test_callback(options: List[Tuple[str, str]], args: List[str]) -> Tuple[str, int]:
    return ("callback", len(args))


def test___sub_usage(verbose: bool = False) -> Tuple[str, bool]:
    message = ""
    result = True

    fun = commandparser.__sub_usage

    if result:
        # Indata format:
        # (command, commandline, mock_exit, expected_result,
        #  expected_exception, expected_exception_msg)
        testdata = (
            (
                "foobar",
                {},
                "errno.EINVAL",
                None,
                Exception,
                "errno.EINVAL",
            ),
            (
                "hello",
                {
                    "Hello World": {
                        "command": ["hello"],
                        "callback": test_callback,
                    },
                },
                "errno.ENOENT",
                None,
                Exception,
                "errno.ENOENT",
            ),
        )

        for command, commandline, mock_exit, \
                expected_result, expected_exception, expected_exception_msg in testdata:
            try:
                with mock.patch("sys.exit", side_effect=Exception(mock_exit)):
                    commandparser.commandline = commandline
                    tmp = fun(command)

                if tmp != expected_result:
                    message = f"{fun.__name__}() did not yield expected result:\n" \
                              f"           result: {tmp}\n" \
                              f"  expected result: {expected_result}"
                    result = False
                    break
                callback, options, args = tmp
                tmp = callback(options, args)
            except Exception as e:
                if expected_exception is not None:
                    if isinstance(e, expected_exception) \
                            and expected_exception_msg is None or expected_exception_msg == str(e):
                        pass
                    else:
                        message = f"{fun.__name__}() did not yield expected result:\n" \
                                  f"        exception: {type(e)}\n" \
                                  f"          message: {str(e)}\n" \
                                  f"         expected: {expected_exception}" \
                                  f" expected message: {expected_exception_msg}"
                        result = False
                        break
                else:
                    message = f"{fun.__name__}() did not yield expected result:\n" \
                              f"        exception: {type(e)}\n" \
                              f"          message: {str(e)}\n" \
                              f"  expected result: {expected_result}"
                    result = False
                    break
    return message, result


def test_parse_commandline(verbose: bool = False) -> Tuple[str, bool]:
    message = ""
    result = True

    fun = commandparser.parse_commandline

    if result:
        # Indata format:
        # (programname, programversion, programdescription, programauthors,
        #  argv, commandline, default_command, expected_result, expected_exception)
        testdata = (
            # No args; no options; no commands
            (
                "clptests",
                "v42",
                "tests for commandparser.py",
                "various people",
                ["clptests", "help"],
                {},
                commandparser.__command_usage,
                (
                    commandparser.__command_usage,
                    [('__commandname', 'help')],
                    [],
                ),
                None,
                None,
            ),
            # No args; global options; no commands
            (
                "clptests",
                "v42",
                "tests for commandparser.py",
                "various people",
                ["clptests", "help"],
                {
                    "__global_options": {
                        "command": ["__global_options"],
                        "description": [ANSIThemeStr("", "")],
                        "options": {
                            "--read-only": {
                                "description":
                                    [ANSIThemeStr("disable all commands that modify state", "description")],
                            },
                        },
                    },
                },
                commandparser.__command_usage,
                (
                    commandparser.__command_usage,
                    [('__commandname', 'help')],
                    [],
                ),
                None,
                None,
            ),
            # No args; global options; no commands; --format markdown
            (
                "clptests",
                "v42",
                "tests for commandparser.py",
                "various people",
                ["clptests", "help", "--format", "markdown"],
                {
                    "__global_options": {
                        "command": ["__global_options"],
                        "description": [ANSIThemeStr("", "")],
                        "options": {
                            "--read-only": {
                                "description":
                                    [ANSIThemeStr("disable all commands that modify state", "description")],
                            },
                        },
                    },
                },
                commandparser.__command_usage,
                (
                    commandparser.__command_usage,
                    [('--format', 'markdown'), ('__commandname', 'help')],
                    [],
                ),
                None,
                None,
            ),
            # No args; global options; command
            (
                "clptests",
                "v42",
                "tests for commandparser.py",
                "various people",
                ["clptests", "help"],
                {
                    "Hello World": {
                        "command": ["hello"],
                        "description": [
                            ANSIThemeStr("Update the package cache and show software versions",
                                         "description")],
                        "extended_description": [
                            [ANSIThemeStr("Note", "note"),
                             ANSIThemeStr(": some of the listed software may not be",
                                          "description")],
                            [ANSIThemeStr("relevant to the configuration in use",
                                          "description")],
                        ],
                        "options": {
                            "--no-args": {
                                "description": [
                                    ANSIThemeStr("This option does not take arguments",
                                                 "description")
                                ],
                            },
                            "--takes-an-integer": {
                                "description": [
                                    ANSIThemeStr("This option takes an integer in the range [2-5]",
                                                 "description")
                                ],
                                "requires_arg": True,
                                "validation": {
                                    "validator": "int",
                                    "valid_range": (2, 5),
                                },
                            },
                        },
                        "required_args": [
                            {
                                "name": "foo_bar_or_baz",
                                "string": [
                                    ANSIThemeStr("foo, bar, or baz", "argument")
                                ],
                                "validation": {
                                    "validator": "allowlist",
                                    "allowlist": ["foo", "bar", "baz"],
                                },
                            },
                        ],
                        "optional_args": [
                            {
                                "name": "foodigitsbar",
                                "string": [
                                    ANSIThemeStr("foo[numbers]bar", "argument")],
                                    "validation": {
                                        "validator": "regex",
                                        "regex": r"^foo\d+bar$",
                                    },
                            },
                        ],
                        "callback": test_callback,
                    },
                    "__global_options": {
                        "command": ["__global_options"],
                        "description": [ANSIThemeStr("", "")],
                        "options": {
                            "--read-only": {
                                "description":
                                    [ANSIThemeStr("disable all commands that modify state", "description")],
                            },
                        },
                    },
                },
                commandparser.__command_usage,
                (
                    commandparser.__command_usage,
                    [('__commandname', 'help')],
                    [],
                ),
                None,
                None,
            ),
            # No args; global options; command; --format markdown
            (
                "clptests",
                "v42",
                "tests for commandparser.py",
                "various people",
                ["clptests", "help", "--format", "markdown"],
                {
                    "Hello World": {
                        "command": ["hello"],
                        "description": [
                            ANSIThemeStr("Update the package cache and show software versions",
                                         "description")],
                        "extended_description": [
                            [ANSIThemeStr("Note", "note"),
                             ANSIThemeStr(": some of the listed software may not be",
                                          "description")],
                            [ANSIThemeStr("relevant to the configuration in use",
                                          "description")],
                        ],
                        "options": {
                            "--no-args": {
                                "description": [
                                    ANSIThemeStr("This option does not take arguments",
                                                 "description")
                                ],
                            },
                            "--takes-an-integer": {
                                "description": [
                                    ANSIThemeStr("This option takes an integer in the range [2-5]",
                                                 "description")
                                ],
                                "requires_arg": True,
                                "validation": {
                                    "validator": "int",
                                    "valid_range": (2, 5),
                                },
                            },
                        },
                        "required_args": [
                            {
                                "name": "foo_bar_or_baz",
                                "string": [
                                    ANSIThemeStr("foo, bar, or baz", "argument")
                                ],
                                "validation": {
                                    "validator": "allowlist",
                                    "allowlist": ["foo", "bar", "baz"],
                                },
                            },
                        ],
                        "optional_args": [
                            {
                                "name": "foodigitsbar",
                                "string": [
                                    ANSIThemeStr("foo[numbers]bar", "argument")],
                                    "validation": {
                                        "validator": "regex",
                                        "regex": r"^foo\d+bar$",
                                    },
                            },
                        ],
                        "callback": test_callback,
                    },
                    "__global_options": {
                        "command": ["__global_options"],
                        "description": [ANSIThemeStr("", "")],
                        "options": {
                            "--read-only": {
                                "description":
                                    [ANSIThemeStr("disable all commands that modify state", "description")],
                            },
                        },
                    },
                },
                commandparser.__command_usage,
                (
                    commandparser.__command_usage,
                    [('--format', 'markdown'), ('__commandname', 'help')],
                    [],
                ),
                None,
                None,
            ),
            (
                "clptests",
                "v42",
                "tests for commandparser.py",
                "various people",
                ["clptests", "hello", "--no-args", "--takes-an-integer", 4, "foo"],
                {
                    "Hello World": {
                        "command": ["hello"],
                        "description": [
                            ANSIThemeStr("Update the package cache and show software versions",
                                         "description")],
                        "extended_description": [
                            [ANSIThemeStr("Note", "note"),
                             ANSIThemeStr(": some of the listed software may not be",
                                          "description")],
                            [ANSIThemeStr("relevant to the configuration in use",
                                          "description")],
                        ],
                        "options": {
                            "--no-args": {
                                "description": [
                                    ANSIThemeStr("This option does not take arguments",
                                                 "description")
                                ],
                            },
                            "--takes-an-integer": {
                                "description": [
                                    ANSIThemeStr("This option takes an integer in the range [2-5]",
                                                 "description")
                                ],
                                "requires_arg": True,
                                "validation": {
                                    "validator": "int",
                                    "valid_range": (2, 5),
                                },
                            },
                        },
                        "required_args": [
                            {
                                "name": "foo_bar_or_baz",
                                "string": [
                                    ANSIThemeStr("foo, bar, or baz", "argument")
                                ],
                                "validation": {
                                    "validator": "allowlist",
                                    "allowlist": ["foo", "bar", "baz"],
                                },
                            },
                        ],
                        "optional_args": [
                            {
                                "name": "foodigitsbar",
                                "string": [
                                    ANSIThemeStr("foo[numbers]bar", "argument")],
                                    "validation": {
                                        "validator": "regex",
                                        "regex": r"^foo\d+bar$",
                                    },
                            },
                        ],
                        "callback": test_callback,
                    },
                    "extended_description": [
                        [ANSIThemeStr("Extended description", "description")],
                    ],
                },
                None,
                (
                    test_callback,
                    [('--no-args', None), ('--takes-an-integer', 4), ('__commandname', 'hello')],
                    ['foo'],
                ),
                None,
                None,
            ),
            (
                "clptests",
                "v42",
                "tests for commandparser.py",
                "various people",
                ["clptests", "help", "hello"],
                {
                    "Hello World": {
                        "command": ["hello"],
                        "values": [
                            ANSIThemeStr("foo", "argument"),
                            ANSIThemeStr("|", "separator"),
                            ANSIThemeStr("bar", "argument"),
                            ANSIThemeStr("|", "separator"),
                            ANSIThemeStr("baz", "argument"),
                        ],
                        "description": [
                            ANSIThemeStr("Update the package cache and show software versions",
                                         "description")],
                        "extended_description": [
                            [ANSIThemeStr("Note", "note"),
                             ANSIThemeStr(": some of the listed software may not be",
                                          "description")],
                            [ANSIThemeStr("relevant to the configuration in use",
                                          "description")],
                        ],
                        "options": {
                            "--no-args": {
                                "description": [
                                    ANSIThemeStr("This option does not take arguments",
                                                 "description")
                                ],
                            },
                            "--takes-another-integer": {
                                "description": [
                                    ANSIThemeStr("This option takes an integer in the range [2-5]",
                                                 "description")
                                ],
                                "values": [
                                    ANSIThemeStr("INT", "argument")],
                                "extended_description": [
                                    [ANSIThemeStr("Potentially", "description")],
                                    [ANSIThemeStr("several", "description")],
                                    [ANSIThemeStr("lines", "description")],
                                ],
                                "requires_arg": True,
                                "validation": {
                                    "validator": "int",
                                    "valid_range": (2, 5),
                                },
                            },
                        },
                        "required_args": [
                            {
                                "name": "foo_bar_or_baz",
                                "string": [
                                    ANSIThemeStr("foo", "argument"),
                                    ANSIThemeStr("|", "separator"),
                                    ANSIThemeStr("bar", "argument"),
                                    ANSIThemeStr("|", "separator"),
                                    ANSIThemeStr("baz", "argument"),
                                ],
                                "validation": {
                                    "validator": "allowlist",
                                    "allowlist": ["foo", "bar", "baz"],
                                },
                            },
                        ],
                        "optional_args": [
                            {
                                "name": "foodigitsbar",
                                "string": [
                                    ANSIThemeStr("foo[numbers]bar", "argument")],
                                    "validation": {
                                        "validator": "regex",
                                        "regex": r"^foo\d+bar$",
                                    },
                            },
                        ],
                        "callback": test_callback,
                    },
                    "extended_description": [
                        [ANSIThemeStr("Extended description", "description")],
                    ],
                },
                None,
                (
                    commandparser.__command_usage,
                    [('__commandname', 'help')],
                    ['hello'],
                ),
                None,
                None,
            ),
            (
                "clptests",
                "v42",
                "tests for commandparser.py",
                "various people",
                ["clptests", "help"],
                {
                    "Hello World": {
                        "command": ["hello"],
                        "description": [
                            ANSIThemeStr("Update the package cache and show software versions",
                                         "description")],
                        "extended_description": [
                            [ANSIThemeStr("Note", "note"),
                             ANSIThemeStr(": some of the listed software may not be",
                                          "description")],
                            [ANSIThemeStr("relevant to the configuration in use",
                                          "description")],
                        ],
                        "required_args": [
                            {
                                "name": "foo_bar_or_baz",
                                "string": [
                                    ANSIThemeStr("foo, bar, or baz", "argument")
                                ],
                                "validation": {
                                    "validator": "allowlist",
                                    "allowlist": ["foo", "bar", "baz"],
                                },
                            },
                        ],
                        "callback": test_callback,
                    },
                },
                None,
                (
                    commandparser.__command_usage,
                    [('__commandname', 'help')],
                    [],
                ),
                None,
                None,
            ),
            (
                "clptests",
                "v42",
                "tests for commandparser.py",
                "various people",
                ["clptests", "help", "--format", "markdown",],
                {
                    "spacer": {
                        "description": [
                        ANSIThemeStr("", "description")],
                    },
                    "__Global": {
                        "description": [
                        ANSIThemeStr("", "description")],
                    },
                    "Hello World": {
                        "command": ["hello"],
                        "description": [
                            ANSIThemeStr("Update the package cache and show software versions",
                                         "description")],
                        "extended_description": [
                            [ANSIThemeStr("Note", "note"),
                             ANSIThemeStr(": some of the listed software may not be",
                                          "description")],
                            [ANSIThemeStr("relevant to the configuration in use",
                                          "description")],
                        ],
                        "callback": test_callback,
                    },
                },
                None,
                (
                    commandparser.__command_usage,
                    [('--format', 'markdown'), ('__commandname', 'help')],
                    [],
                ),
                None,
                None,
            ),
            (
                "clptests",
                "v42",
                "tests for commandparser.py",
                "various people",
                ["clptests", "help"],
                {
                    "Hello World": {
                        "command": ["hello"],
                        "description": [
                            ANSIThemeStr("Update the package cache and show software versions",
                                         "description")],
                        "extended_description": [
                            [ANSIThemeStr("Note", "note"),
                             ANSIThemeStr(": some of the listed software may not be",
                                          "description")],
                            [ANSIThemeStr("relevant to the configuration in use",
                                          "description")],
                        ],
                        "callback": test_callback,
                    },
                },
                None,
                (
                    commandparser.__command_usage,
                    [('__commandname', 'help')],
                    [],
                ),
                None,
                None,
            ),
            (
                "clptests",
                "v42",
                "tests for commandparser.py",
                "various people",
                ["clptests", "help", "--format", "markdown", "version"],
                {
                    "Hello World": {
                        "command": ["hello"],
                        "description": [
                            ANSIThemeStr("Update the package cache and show software versions",
                                         "description")],
                        "extended_description": [
                            [ANSIThemeStr("Note", "note"),
                             ANSIThemeStr(": some of the listed software may not be",
                                          "description")],
                            [ANSIThemeStr("relevant to the configuration in use",
                                          "description")],
                        ],
                        "callback": test_callback,
                    },
                },
                None,
                (
                    commandparser.__command_usage,
                    [('--format', 'markdown'), ('__commandname', 'help')],
                    ['version'],
                ),
                None,
                None,
            ),
            (
                "clptests",
                "v42",
                "tests for commandparser.py",
                "various people",
                ["clptests", "version"],
                {
                    "Hello World": {
                        "command": ["hello"],
                        "description": [
                            ANSIThemeStr("Update the package cache and show software versions",
                                         "description")],
                        "extended_description": [
                            [ANSIThemeStr("Note", "note"),
                             ANSIThemeStr(": some of the listed software may not be",
                                          "description")],
                            [ANSIThemeStr("relevant to the configuration in use",
                                          "description")],
                        ],
                        "callback": test_callback,
                    },
                },
                None,
                (
                    commandparser.__version,
                    [('__commandname', 'version')],
                    [],
                ),
                None,
                None,
            ),
            (
                "clptests",
                "v42",
                "tests for commandparser.py",
                "various people",
                ["clptests", "help"],
                {
                    "__global_options": {
                        "command": ["__global_options"],
                        "description": [
                            ANSIThemeStr("", "")],
                        "options": {
                            "--happiness": {
                                "description": [
                                    ANSIThemeStr("Be happier", "description")],
                            },
                        },
                    },
                },
                commandparser.__command_usage,
                (
                    commandparser.__command_usage,
                    [('__commandname', 'help')],
                    [],
                ),
                None,
                None,
            ),
            (
                "clptests",
                "v42",
                "tests for commandparser.py",
                "various people",
                ["clptests", "\x00help"],
                {},
                None,
                None,
                Exception,
                str(errno.EINVAL),
            ),
        )

        for programname, programversion, programdescription, programauthors, \
                argv, commandline, default_command, \
                expected_result, expected_exception, expected_exception_msg in testdata:
            try:
                with mock.patch("sys.exit", side_effect=Exception(str(errno.EINVAL))):
                    tmp = fun(programname, programversion, programdescription, programauthors,
                              argv, commandline, default_command, theme=DEFAULT_THEME_FILE)

                if tmp != expected_result:
                    message = f"{fun.__name__}() did not yield expected result:\n" \
                              f"           result: {tmp}\n" \
                              f"  expected result: {expected_result}"
                    result = False
                    break
                callback, options, args = tmp
                tmp = callback(options, args)
            except Exception as e:
                if expected_exception is not None:
                    if isinstance(e, expected_exception) \
                            and expected_exception_msg is None or expected_exception_msg == str(e):
                        pass
                    else:
                        message = f"{fun.__name__}() did not yield expected result:\n" \
                                  f"        exception: {type(e)}\n" \
                                  f"          message: {str(e)}\n" \
                                  f"         expected: {expected_exception}" \
                                  f" expected message: {expected_exception_msg}"
                        result = False
                        break
                else:
                    message = f"{fun.__name__}() did not yield expected result:\n" \
                              f"        exception: {type(e)}\n" \
                              f"          message: {str(e)}\n" \
                              f"  expected result: {expected_result}"
                    result = False
                    break
    return message, result


def test___find_command(verbose: bool = False) -> Tuple[str, bool]:
    message = ""
    result = True

    fun = commandparser.__find_command

    if result:
        # Indata format:
        # (commandline, arg, expected_result, expected_exception)
        testdata = (
            # Valid commandline, existing command
            (
                {
                    "Hello World": {
                        "command": ["hello"],
                        "description": [
                            ANSIThemeStr("Update the package cache and show software versions",
                                         "description")],
                        "extended_description": [
                            [ANSIThemeStr("Note", "note"),
                             ANSIThemeStr(": some of the listed software may not be",
                                          "description")],
                            [ANSIThemeStr("relevant to the configuration in use",
                                          "description")],
                        ],
                        "callback": test_callback,
                    },
                },
                "hello",
                ('hello', test_callback, 'Hello World', 0, 0, [], []),
                None,
            ),
            # Valid commandline, non-existing command
            (
                {
                    "Hello World": {
                        "command": ["hello"],
                        "description": [
                            ANSIThemeStr("Update the package cache and show software versions",
                                         "description")],
                        "extended_description": [
                            [ANSIThemeStr("Note", "note"),
                             ANSIThemeStr(": some of the listed software may not be",
                                          "description")],
                            [ANSIThemeStr("relevant to the configuration in use",
                                          "description")],
                        ],
                        "callback": test_callback,
                    },
                },
                "foo",
                ('', None, 'Hello World', 0, 0, [], []),
                None,
            ),
            # Empty commandline
            (
                {},
                "foo",
                ('', None, '', 0, 0, [], []),
                None,
            ),
        )

        for commandline, arg, expected_result, expected_exception in testdata:
            try:
                tmp = fun(commandline, arg)

                if tmp != expected_result:
                    message = f"{fun.__name__}() did not yield expected result:\n" \
                              f"           result: {tmp}\n" \
                              f"  expected result: {expected_result}"
                    result = False
                    break
            except Exception as e:
                if expected_exception is not None:
                    if isinstance(e, expected_exception) and expected_exception_msg is None:
                        pass
                    else:
                        message = f"{fun.__name__}() did not yield expected result:\n" \
                                  f"        exception: {type(e)}\n" \
                                  f"          message: {str(e)}\n" \
                                  f"         expected: {expected_exception}"
                        result = False
                        break
                else:
                    message = f"{fun.__name__}() did not yield expected result:\n" \
                              f"        exception: {type(e)}\n" \
                              f"          message: {str(e)}\n" \
                              f"  expected result: {expected_result}"
                    result = False
                    break
    return message, result


tests: Dict = {
    ("__sub_usage()",): {
        "callable": test___sub_usage,
        "result": None,
    },
    ("parse_commandline()",): {
        "callable": test_parse_commandline,
        "result": None,
    },
    ("__find_command()",): {
        "callable": test___find_command,
        "result": None,
    },
}


def main() -> int:
    fail = 0
    success = 0
    verbose = False
    failed_testcases = []

    init_ansithemeprint(themefile=None)

    # How many non-prepare testcases do we have?
    testcount = sum(1 for i in tests if not deep_get(tests[i], DictPath("prepare"), False))
    start_at_task = 0
    end_at_task = testcount

    i = 1

    while i < len(sys.argv):
        opt = sys.argv[i]
        optarg = None
        if i + 1 < len(sys.argv):
            optarg = sys.argv[i + 1]
        if opt == "--start-at":
            if not (isinstance(optarg, str) and optarg.isnumeric()):
                raise ValueError("--start-at TASK requires an integer "
                                 f"in the range [0,{testcount}]")
            start_at_task = int(optarg)
            i += 1
        elif opt == "--end-at":
            if not (isinstance(optarg, str) and optarg.isnumeric()):
                raise ValueError(f"--end-at TASK requires an integer in the range [0,{testcount}]")
            end_at_task = int(optarg)
            i += 1
        else:
            sys.exit(f"Unknown argument: {opt}")
        i += 1

    for i, test in enumerate(tests):
        if i < start_at_task:
            continue
        if i > end_at_task:
            break
        ansithemeprint([ANSIThemeStr(f"[{i:03}/{testcount - 1:03}]", "emphasis"),
                        ANSIThemeStr(f" {', '.join(test)}:", "default")])
        message, result = tests[test]["callable"](verbose=verbose)
        if message:
            ansithemeprint([ANSIThemeStr("  FAIL", "error"),
                            ANSIThemeStr(f": {message}", "default")])
        else:
            ansithemeprint([ANSIThemeStr("  PASS", "success")])
            success += 1
        tests[test]["result"] = result
        if not result:
            fail += 1
            failed_testcases.append(f"{i}: {', '.join(test)}")

    ansithemeprint([ANSIThemeStr("\nSummary:", "header")])
    if fail:
        ansithemeprint([ANSIThemeStr(f"  FAIL: {fail}", "error")])
    else:
        ansithemeprint([ANSIThemeStr(f"  FAIL: {fail}", "unknown")])
    ansithemeprint([ANSIThemeStr(f"  PASS: {success}", "success")])

    if fail:
        ansithemeprint([ANSIThemeStr("\nFailed testcases:", "header")])
        for testcase in failed_testcases:
            ansithemeprint([ANSIThemeStr("  • ", "separator"),
                            ANSIThemeStr(testcase, "default")], stderr=True)
        sys.exit(fail)

    return 0


if __name__ == "__main__":
    main()
