#! /usr/bin/env python3

import json
try:
	import jsonschema
except ModuleNotFoundError:
	sys.exit("ModuleNotFoundError: you probably need to install python3-jsonschema")

import os
import yaml
import sys

verbose = True
abort_on_fail = True

failed_files = []

def usage():
	print("validate_yaml [ARGUMENTS]\n")
	print("Validate YAML files used by iKT\n")
	print("themes|views|parsers                 Validate all YAML-files in the default directory for the specified type")
	print("themes|views|parsers|SCHEMA PATH...  Validate all YAML-files at PATH for the specified type")
	print("                                     if PATH is a directory, or the specified file if PATH is a file")
	print("")
	print("If no arguments are specified all YAML-files will be validated")
	print("If the schema isn't one of themes|views|parsers it'll be expected to be a path to a valid JSON schema file\n")
	print("Built-in paths are relative to the base directory of the iKT source code\n")
	print("Note: No schemas are available to validate playbooks; use ansible-playbook to validate playbooks\n")
#	print("--verbose          Output version information and exit")
	print("help|--help        Display this help and exit")
#	print("version|--version  Output version information and exit")

def validate_file(yaml_path, schema_path):
	if not yaml_path.endswith((".yaml", ".yml")):
		print(f"\n{yaml_path} does not end in .yaml or .yml; skipping.\n")
		return -1

	if not os.path.isfile(yaml_path):
		print(f"\n{yaml_path} is not a file; skipping.\n")
		return -1

	yaml_data = {}

	if not os.path.isfile(schema_path):
		sys.exit(f"schema {schema_path} does not exist or is not a file; aborting.")

	with open(schema_path, "r") as f:
		try:
			schema = json.load(f)
		except json.decoder.JSONDecodeError as e:
			print(f"\nThe schema file {schema_path} is not valid JSON:")
			sys.exit(f"\njson.decoder.JSONDecodeError: {e}")

	with open(yaml_path, "r") as f:
		yaml_data = yaml.safe_load(f)

	if verbose == True:
		print(f"Validating {yaml_path} with {schema_path}")

	fail = 0

	try:
		jsonschema.validate(schema = schema, instance = yaml_data)
	except jsonschema.exceptions.SchemaError as e:
		print(f"\nFailed to validate schema {schema_path}")
		sys.exit(f"\njsonschema.exceptions.SchemaError: {e}")
	except jsonschema.exceptions.ValidationError as e:
		print(f"\n  Failed to validate {yaml_path} using {schema_path}\n")
		if abort_on_fail == True:
			sys.exit(f"\njsonschema.exceptions.ValidationError: {e}")
		failed_files.append(yaml_path)
		fail = 1

	return fail

def main():
	if len(sys.argv) == 2 and sys.argv[1] in ["help", "--help"]:
		usage()
		sys.exit(0)

	if len(sys.argv) == 1:
		yaml_paths = [
			("themes", "tests/schemas/themes.json"),
			("views", "tests/schemas/views.json"),
			("parsers", "tests/schemas/parsers.json"),
		]
	else:
		schema = sys.argv[1]
		if schema in ["themes", "views", "parsers"]:
			schema_path = f"tests/schemas/{schema}.json"
		else:
			schema_path = schema
			if not os.path.isfile(schema_path) or not schema_path.lower().endswith(".json"):
				sys.exit(f"SCHEMA has to be a path to a JSON schema file")

	if len(sys.argv) == 2:
		yaml_paths = [
			(schema, f"tests/schemas/{schema}.json")
		]
	elif len(sys.argv) > 2:
		yaml_paths = []
		for path in sys.argv[2:]:
			yaml_paths.append((path, schema_path))

	count = 0
	successful = 0
	fail = 0
	skip = 0

	for yaml_path, schema in yaml_paths:
		if os.path.isfile(yaml_path):
			validate_file(yaml_path, schema)
		elif os.path.isdir(yaml_path):
			for path in os.listdir(yaml_path):
				retval = validate_file(f"{yaml_path}/{path}", schema)
				if retval == -1:
					skip += 1
				else:
					fail += retval
		count += 1

	print(f"\nSummary:")
	if abort_on_fail == False:
		print(f"     fail: {fail}")
	print(f"     skip: {skip}")
	print(f"  success: {count - fail}")
	print(f"    total: {count}")

	print("\n\nThe following files failed validation:")
	print("---")
	for file in failed_files:
		print(f"  {file}")

if __name__ == "__main__":
	main()
