---
kind: "__PrometheusRuleData"
api_family: "monitoring.coreos.com"
default_command: "__"
infoview:
  name: "Prometheus Rule Data"
  annotations: null
  labels: null
  infopad:
    name_path: ""
    creation_timestamp_path: ""
    row_indexes:
      Normal:
        fields: ["name", "group", "rule_type", "duration"]
    rows:
      duration:
        header: [["Duration:", ["main", "infoheader"]]]
        path: "for"
        default: "<unset>"
        type: "str"
        formatter: "numerical"
      group:
        header: [["Group:", ["main", "infoheader"]]]
        path: "_extra_data#group"
        type: "raw"
      name:
        header: [["Name:", ["main", "infoheader"]]]
        path: "_extra_data#name"
        type: "raw"
      rule_type:
        header: [["Rule Type:", ["main", "infoheader"]]]
        path: "_extra_data#rtype"
        type: "raw"
  logpad:
    infogetter: "logpad_msg_getter"
    infogetter_args:
      path: "expr"
    timestamps: false
  shortcuts:
    # __PrometheusRuleData has no YAML, last applied configuration, or events
    "Last Applied Configuration": null
    "Show Events": null
    "YAML": null
