kind: Alertmanager
api_family: monitoring.coreos.com
default_command: alertmanagers
command:
- alm
listview:
  name: Alertmanagers
  group: Monitoring
  field_indexes:
    Normal: [namespace, name, version] #, replicas, age]
  fields:
    version:
      header: "Version:"
      path: "spec#version"
      type: version
