kind: "Alertmanager"
api_family: "monitoring.coreos.com"
default_command: "alertmanagers"
command:
- "alm"
listview:
  name: "Alertmanagers"
  group: "Monitoring"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "version", "replicas", "age"]
      sortcolumn: "namespace"
  fields:
    replicas:
      header: "Replicas:"
      path: "spec#replicas"
      type: "int"
      formatting:
        field_colors:
        - type: "numerical"
      align: "right"
    version:
      header: "Version:"
      path: "spec#version"
      type: "str"
      formatting:
        field_colors:
        - type: "version"
infoview:
  name: "Alertmanager Info"
  infopad:
    row_indexes:
      Normal:
        fields:
        - "image"
        - "external_url"
        - "listen_local"
        - "log_format"
        - "loglevel"
        - "retention"
        - "port_name"
        - "route_prefix"
        - "node_selector"
        - "paused"
        - "replicas"
        - "service_account"
    rows:
      external_url:
        header: [["External URL:", ["main", "infoheader"]]]
        path: "spec#externalUrl"
        type: "str"
      image:
        header: [["Image:", ["main", "infoheader"]]]
        paths:
        - path: "spec#image"
          pathtype: "regex"
          regex: "^([^:]+):(.*)"
        formatter: "list"
        formatting:
          field_colors:
          - type: "generic"
          - type: "version"
          field_separators:
          - type: "version"
      listen_local:
        header: [["Listen Local:", ["main", "infoheader"]]]
        path: "spec#listenLocal"
        type: "bool"
      log_format:
        header: [["Log Format:", ["main", "infoheader"]]]
        path: "spec#logFormat"
        type: "str"
      loglevel:
        header: [["Loglevel:", ["main", "infoheader"]]]
        path: "spec#logLevel"
        type: "str"
      node_selector:
        header: [["Node Selector:", ["main", "infoheader"]]]
        paths:
        - path: ["spec#nodeSelector"]
          pathtype: "key_value"
        formatter: "list"
        formatting:
          field_colors:
          - type: "key"
          - type: "value"
          field_separators:
          - type: "selector"
      paused:
        header: [["Paused:", ["main", "infoheader"]]]
        path: "spec#paused"
        type: "bool"
      port_name:
        header: [["Port Name:", ["main", "infoheader"]]]
        path: "spec#portName"
        type: "str"
      replicas:
        header: [["Replicas:", ["main", "infoheader"]]]
        path: "spec#replicas"
        type: "int"
        formatting:
          field_colors:
          - type: "numerical"
      retention:
        header: [["Retention:", ["main", "infoheader"]]]
        path: "spec#retention"
        type: "str"
        formatter: "age"
      route_prefix:
        header: [["Route Prefix:", ["main", "infoheader"]]]
        path: "spec#routePrefix"
        type: "str"
      service_account:
        header: [["S", ["main", "infoheader_shortcut"]], ["ervice Account:", ["main", "infoheader"]]]
        path: "spec#serviceAccountName"
        type: "str"
  listpad:
    listgetter: "listgetter_join_dicts_to_list"
    listgetter_args:
      key_paths: ["spec#resources#limits", "spec#resources#requests"]
      key_name: "resource"
      fields:
      - path: "spec#resources#limits"
        name: "limit"
        default:
      - path: "spec#resources#requests"
        name: "request"
        default:
    infogetter: "generic_infogetter"
    field_indexes:
      Normal:
        fields: ["resource", "request", "limit"]
        sortcolumn: "resource"
    fields:
      limit:
        header: "Limit:"
        path: "limit"
        type: "raw"
      resource:
        header: "Resource:"
        path: "resource"
        type: "str"
      request:
        header: "Request:"
        path: "request"
        type: "raw"
  shortcuts:
    "Service Account":
      key: "s"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Service Account"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        kind: "ServiceAccount"
        namespace_path: "metadata#namespace"
        name_path: "spec#serviceAccountName"
    "Containers":
      key: "c"
      modifier: "shift"
      read_only: true
      helptext: "List containers"
      widget: "windowwidget"
      title: "Containers:"
      selectable: true
      itemgetter: "get_list_fields"
      itemgetter_args:
        path: "spec#containers"
        fields:
        - "name"
        pass_ref: true
      action: "call"
      action_call: "view_yaml"
      action_args:
        title: "Container Information"
        _named_title: true
        _name_path: "name"
    "Show affinities":
      key: "a"
      modifier: "shift"
      read_only: true
      helptext: "Show affinities"
      widget: "windowwidget"
      headers: ["Type:", "Scheduling:", "Execution:", "Selector:", "Topology:"]
      itemgetter: "get_pod_affinity"
      # This isn't supported for now
      sortcolumn: "type"
