kind: "APIServer"
api_family: "config.openshift.io"
default_command: "apiservers.config.openshift.io"
command:
- "apiservers.config"
- "apiserver.config"
listview:
  name: "API Servers (Config)"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "API Server Info (OpenShift Config)"
  infopad:
    row_indexes:
      Normal:
        fields: ["client_ca", "cluster_version", "audit_profile", "encryption_type", "tls_security_profile"]
    rows:
      audit_profile:
        header: [["Audit Profile:", ["main", "infoheader"]]]
        path: "spec#audit#profile"
        type: "str"
      client_ca:
        header: [["C", ["main", "infoheader_shortcut"]], ["lient CA:", ["main", "infoheader"]]]
        path: "spec#clientCA#name"
        default: "<none>"
        type: "str"
      cluster_version:
        header: [["Cluster ", ["main", "infoheader"]], ["V", ["main", "infoheader_shortcut"]], ["ersion:", ["main", "infoheader"]]]
        paths:
        - path: "metadata#ownerReferences"
          pathtype: "items"
          subpaths:
          - "name"
          when:
          - key: "kind"
            eq: "ClusterVersion"
        default: "<none>"
      encryption_type:
        header: [["Encryption Type:", ["main", "infoheader"]]]
        path: "spec#encryption#type"
        default: "<default>"
        type: "str"
      tls_security_profile:
        header: [["TLS Security Profile:", ["main", "infoheader"]]]
        path: "spec#tlsSecurityProfile#type"
        default: "<default>"
        type: "str"
  shortcuts:
    "Additional CORS Allowed Origins":
      key: "o"
      modifier: "shift"
      read_only: true
      helptext: "List additional CORS allowed origins"
      widget: "windowwidget"
      title: "CORS allowed origins:"
      selectable: true
      itemgetter: "get_list_as_list"
      itemgetter_args:
        paths: ["spec#additionalCORSAllowedOrigins"]
      # Not supported for now
      sortcolumn: "origin"
    "Client CA":
      key: "c"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for client CA"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        namespace: "openshift-config"
        name_path: "spec#clientCA#name"
        kind: "ConfigMap"
    "Cluster Version":
      key: "v"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Cluster Version"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        owner_reference_path: "metadata#ownerReferences"
        kind: "ClusterVersion"
        api_family: "config.openshift.io"
    "View serving certs":
      key: "s"
      modifier: "shift"
      read_only: true
      helptext: "View serving TLS certificates"
      action: "call"
      action_call: "view_yaml"
      action_args:
        title: "Service TLS certificates"
        _pass_obj: true
        path: "spec#servingCerts"
