kind: Authentication
api_family: config.openshift.io
default_command: authentications.config.openshift.io
listview:
  name: Authentications
  group: OpenShift
  field_indexes:
    Normal: [name, age]
