---
kind: "AuthConfig"
api_family: "management.cattle.io"
default_command: "authconfigs.management.cattle.io"
command:
  - "authconfigs.cattle"
  - "authconfig.cattle"
  - "authconfs.cattle"
  - "authconf.cattle"
listview:
  name: "Auth Configs"
  group: "Rancher"
  field_indexes:
    Normal:
      fields: ["name", "type", "age"]
  fields:
    type:
      header: "Type:"
      path: "type"
      default: "<unset>"
      type: "str"
infoview:
  name: "Auth Config Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["type", "logout_all_supported"]
    rows:
      logout_all_supported:
        header: [["Logout All Supported:", ["main", "infoheader"]]]
        path: "type"
        default: "<unset>"
        type: "bool"
      type:
        header: [["Type:", ["main", "infoheader"]]]
        path: "type"
        default: "<unset>"
        type: "str"
