---
kind: "BGPConfiguration"
api_family: "crd.projectcalico.org"
default_command: "bgpconfigurations"
listview:
  name: "BGP Configurations"
  group: "Calico"
  field_indexes:
    Normal:
      fields: ["name", "age"]
