kind: Build
api_family: config.openshift.io
default_command: builds.config.openshift.io
command:
- builds.config
- build.config
listview:
  name: Builds (Config)
  group: OpenShift
  field_indexes:
    Normal: [name, age]
