---
kind: "Build"
api_family: "config.openshift.io"
default_command: "builds.config.openshift.io"
command:
  - "builds.config"
  - "build.config"
listview:
  name: "Builds"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "Build Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["cluster_version"]
    rows:
      cluster_version:
        header: [["Cluster ", ["main", "infoheader"]],
                 ["V", ["main", "infoheader_shortcut"]],
                 ["ersion:", ["main", "infoheader"]]]
        paths:
          - path: "metadata#ownerReferences"
            pathtype: "items"
            subpaths:
              - "name"
            when:
              - key: "kind"
                eq: "ClusterVersion"
        default: "<none>"
  shortcuts:
    "Cluster Version":
      key: "v"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Cluster Version"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        owner_reference_path: "metadata#ownerReferences"
        kind: "ClusterVersion"
        api_family: "config.openshift.io"
