kind: "CDIConfig"
api_family: "cdi.kubevirt.io"
default_command: "cdiconfigs"
listview:
  name: "CDI Configs"
  group: "Storage & Backups"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "CDI Config Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["controller", "feature_gates", "tls_security_profile_type", "scratch_space_storage_class"]
    rows:
      controller:
        header: [["C", ["main", "infoheader_shortcut"]], ["ontroller:", ["main", "infoheader"]]]
        paths:
        - path: "metadata#ownerReferences"
          pathtype: "items"
          subpaths:
          - "kind"
          - "apiVersion"
          - "name"
          when:
          - key: "controller"
            eq: true
          type: ["kind", "api_group", "name"]
        default: "<none>"
        formatter: "list"
        formatting:
          field_colors:
          - type: "kind"
          - type: "api_group"
          - type: "generic"
          field_separators:
          - type: "kind_api_group"
          - type: "kind"
      feature_gates:
        header: [["Feature Gates:", ["main", "infoheader"]]]
        path: "spec#featureGates"
        type: "raw"
        formatter: "list"
      scratch_space_storage_class:
        header: [["Scratch Space Storage Class:", ["main", "infoheader"]]]
        path: "status#scratchSpaceStorageClass"
        type: "str"
      tls_security_profile_type:
        header: [["TLS Security Profile Type:", ["main", "infoheader"]]]
        path: "spec#tlsSecurityProfile#type"
        type: "str"
  shortcuts:
    "Open controller":
      key: "c"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for controller"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        namespace_path: "metadata#namespace"
        owner_reference_path: "metadata#ownerReferences"
    "Show proxy settings":
      key: "p"
      modifier: "shift"
      read_only: true
      helptext: "Show proxy settings"
      widget: "windowwidget"
      title: "Proxy settings:"
      headers: ["Protocol:", "URL:"]
      itemgetter: "get_key_value"
      itemgetter_args:
        path: "status#importProxy"
      # Not supported for now
      sortcolumn: "protocol"
