kind: "ClusterConfiguration"
api_family: "installer.kubesphere.io"
default_command: "clusterconfigurations.ks"
command:
- "clrconfs.ks"
- "clrconf.ks"
listview:
  name: "Cluster Configurations"
  group: "KubeSphere"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
