kind: "ClusterOperator"
api_family: "config.openshift.io"
default_command: "clusteroperators"
command:
- "clusteroperators.config"
- "clusteroperator.config"
listview:
  name: "Cluster Operators (Config)"
  group: "OpenShift"
  field_indexes:
    Normal: ["name", "version", "available", "progressing", "degraded", "age"]
  fields:
    available:
      header: "Available:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
          key: "type"
          eq: "Available"
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
    degraded:
      header: "Degraded:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
          key: "type"
          eq: "Degraded"
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_not_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_ok"
    progressing:
      header: "Progressing:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
          key: "type"
          eq: "Progressing"
      type: "str"
    version:
      header: "Version:"
      paths:
      - path: "status#versions"
        pathtype: "items"
        subpath: "version"
        when:
          key: "name"
          eq: "operator"
        default: ["<unset>"]
      type: "str"
      formatting:
        field_colors:
        - type: "version"
infoview:
  name: "Cluster Operator Info"
  infopad:
    row_indexes:
      Normal: ["operator_versions", "cluster_version"]
    rows:
      cluster_version:
        header: [["Cluster ", ["main", "infoheader"]], ["V", ["main", "infoheader_shortcut"]], ["ersion:", ["main", "infoheader"]]]
        paths:
        - path: "metadata#ownerReferences"
          pathtype: "items"
          subpaths:
          - "name"
          when:
            key: "kind"
            eq: "ClusterVersion"
        default: "<none>"
      operator_versions:
        header: [["Operator Versions:", ["main", "infoheader"]]]
        paths:
        - path: "status#versions"
          pathtype: "items"
          subpaths:
          - name
          - version
        formatter: "list"
        formatting:
          field_colors:
          - type: "generic"
          - type: "version"
          field_separators:
          - type: "version"
  listpad:
    on_activation:
      call: "resourceinfodispatch_with_lookup_on_activation"
      kind_path: "resource"
      api_family_path: "group"
      name_path: "name"
      namespace_path: "namespace"
    path: "status#relatedObjects"
    infogetter: "generic_infogetter"
    field_indexes:
      Normal: ["resource", "api_group", "namespace", "name"]
    fields:
      api_group:
        header: "API-Group:"
        path: "group"
        type: "str"
        formatting:
          field_colors:
          - type: "api_group"
      name:
        header: "Name:"
        path: "name"
        type: "str"
      namespace:
        header: "Namespace:"
        path: "namespace"
        type: "str"
        formatting:
          field_colors:
          - type: "namespace"
      resource:
        header: "Resource:"
        path: "resource"
        type: "str"
  shortcuts:
    "Cluster Version":
      key: "v"
      modifier: "shift"
      helptext: "Open info page for Cluster Version"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        owner_reference_path: "metadata#ownerReferences"
        kind: "ClusterVersion"
        api_family: "config.openshift.io"
