kind: "ClusterVersion"
api_family: "config.openshift.io"
default_command: "clusterversions"
command:
- "clusterversions.config.openshift.io"
- "clusterversions.config"
- "clusterversion.config"
listview:
  name: "Cluster Versions"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "version", "available", "progressing", "age", "status"]
  fields:
    available:
      header: "Available:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpaths:
        - "status"
        when:
        - key: "type"
          eq: "Available"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
            "<unknown>":
              field_colors:
              - context: "main"
                type: "status_unknown"
    progressing:
      header: "Progressing:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpaths:
        - "status"
        when:
        - key: "type"
          eq: "Progressing"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
            "<unknown>":
              field_colors:
              - context: "main"
                type: "status_unknown"
    status:
      header: "Status:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpaths:
        - "message"
        when:
        - key: "type"
          eq: "Progressing"
    version:
      header: "Version:"
      paths:
      - path: "status#history"
        pathtype: "items"
        subpaths:
        - "version"
        when:
        - key: "state"
          eq: "Completed"
      type: "str"
      formatting:
        field_colors:
        - type: "version"
infoview:
  name: "Cluster Version Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["channel", "cluster_id", "desired_channels", "desired_image", "desired_url", "desired_version"]
    rows:
      channel:
        header: [["Channel:", ["main", "infoheader"]]]
        path: "spec#channel"
        type: "str"
      cluster_id:
        header: [["Cluster ID:", ["main", "infoheader"]]]
        path: "spec#clusterID"
        type: "str"
      desired_channels:
        header: [["Desired Channel:", ["main", "infoheader"]]]
        path: "status#desired#channels"
        type: "raw"
        formatter: "list"
      desired_image:
        header: [["Desired Image:", ["main", "infoheader"]]]
        path: "status#desired#image"
        type: "str"
      desired_url:
        header: [["Desired URL:", ["main", "infoheader"]]]
        path: "status#desired#url"
        type: "str"
      desired_version:
        header: [["Desired Version:", ["main", "infoheader"]]]
        path: "status#desired#version"
        type: "str"
        formatting:
          field_colors:
          - type: "version"
  listpad:
    on_activation:
      call: "resourceinfodispatch_with_lookup_on_activation"
      kind_path: "kind"
      api_family_path: "group"
      namespace_path: "namespace"
      name_path: "name"
    listgetter: "listgetter_path"
    listgetter_args:
      path: "spec#overrides"
    infogetter: "generic_infogetter"
    field_indexes:
      Normal:
        fields: ["namespace", "name", "kind", "unmanaged"]
        sortcolumn: "namespace"
    fields:
      kind:
        header: "Kind:"
        paths:
        - path: [["kind"], ["group"]]
          pathtype: "tuple"
        formatter: "list"
        formatting:
          field_colors:
          - type: "kind"
          - type: "api_group"
          field_separators:
          - type: "kind_api_group"
      name:
        header: "Name:"
        path: "name"
        type: "str"
      namespace:
        header: "Namespace:"
        path: "namespace"
        type: "str"
        formatting:
          field_colors:
          - type: "namespace"
      unmanaged:
        header: "Unmanaged:"
        path: "unmanaged"
        type: "bool"
