kind: "ClusterConfigAuditReport"
api_family: "aquasecurity.github.io"
default_command: "clusterconfigauditreports"
command:
- "clusterconfigaudits"
- "clusterconfigaudit"
listview:
  name: "Cluster Config Audit Reports"
  group: "Security"
  field_indexes:
    Normal:
      fields: ["name", "age"]
