kind: "Config"
api_family: "imageregistry.operator.openshift.io"
default_command: "configs.imageregistry.operator.openshift.io"
command:
- "configs.imageregistry"
- "config.imageregistry"
listview:
  name: "Configs"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
