kind: Config
api_family: samples.operator.openshift.io
default_command: configs.samples.operator.openshift.io
listview:
  name: Configs (Samples Operator)
  group: OpenShift
  field_indexes:
    Normal: [name, age]
