---
kind: "Configuration"
api_family: "serving.knative.dev"
default_command: "configurations.serving.knative.dev"
command:
- "configurations.knative"
- "configuration.knative"
- "confs.knative"
- "conf.knative"
listview:
  name: "Configurations"
  group: "Knative"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age", "ready", "reason"]
      sortcolumn: "namespace"
  fields:
    ready:
      header: "Ready:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
        - key: "type"
          eq: "Ready"
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
    reason:
      header: "Reason:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "message"
        when:
        - key: "type"
          eq: "Ready"
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
infoview:
  name: "Configuration Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["controller", "latest_created_revision", "latest_ready_revision"]
    rows:
      controller:
        header: [["C", ["main", "infoheader_shortcut"]], ["ontroller:", ["main", "infoheader"]]]
        paths:
        - path: "metadata#ownerReferences"
          pathtype: "items"
          subpaths:
          - "kind"
          - "apiVersion"
          - "name"
          when:
          - key: "controller"
            eq: true
          type: ["kind", "api_group", "name"]
        default: "<none>"
        formatter: "list"
        formatting:
          field_colors:
          - type: "kind"
          - type: "api_group"
          - type: "generic"
          field_separators:
          - type: "kind_api_group"
          - type: "kind"
      latest_created_revision:
        header: [["Latest Crea", ["main", "infoheader"]], ["t", ["main", "infoheader_shortcut"]], ["ed Revision:", ["main", "infoheader"]]]
        path: "status#latestCreatedRevisionName"
        type: "str"
      latest_ready_revision:
        header: [["Latest ", ["main", "infoheader"]], ["R", ["main", "infoheader_shortcut"]], ["eady Revision:", ["main", "infoheader"]]]
        path: "status#latestReadyRevisionName"
        type: "str"
  shortcuts:
    "Open controller":
      key: "c"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for controller"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        namespace_path: "metadata#namespace"
        owner_reference_path: "metadata#ownerReferences"
    "Open latest created revision":
      key: "t"
      read_only: true
      helptext: "Open info page for latest created Revision"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        kind: "Revision"
        api_family: "serving.knative.dev"
        name_path: "status#latestCreatedRevisionName"
        namespace_path: "metadata#namespace"
    "Open latest ready revision":
      key: "r"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for latest ready Revision"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        kind: "Revision"
        api_family: "serving.knative.dev"
        name_path: "status#latestReadyRevisionName"
        namespace_path: "metadata#namespace"
    "View Pod Template":
      key: "p"
      modifier: "shift"
      read_only: true
      helptext: "Show Pod Template"
      action: "call"
      action_call: "view_yaml"
      action_args:
        title: "Pod Template"
        _named_title: true
        _pass_obj: true
        path: "spec#template"
