kind: "ConfigMap"
default_command: "configmaps"
command:
- "cm"
listview:
  name: "Config Maps"
  group: "Core"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "data", "immutable", "age"]
      sortcolumn: "namespace"
  fields:
    data:
      header: "# of Data:"
      path: "data"
      type: "len"
      formatting:
        field_colors:
        - type: "numerical"
      align: "right"
    immutable:
      header: "Immutable:"
      paths:
      - path: "immutable"
        pathtype: "value"
        type: "bool"
        default: ""
infoview:
  name: "Config Map Info"
  listpad:
    on_activation:
      call: "resourceinfodispatch"
      kind: "__ResourceView"
      formatter: "identify"
      formatter_path: "formatter"
      obj_path: "data"
      title_path: "configmap"
    listgetter: "listgetter_configmap_data"
    infogetter: "generic_infogetter"
    field_indexes:
      Normal:
        fields: ["data", "type"]
        sortcolumn: "data"
    fields:
      data:
        header: "Data:"
        path: "configmap"
        type: "str"
      type:
        header: "Type:"
        path: "type"
        type: "str"
  shortcuts:
    "Attempt to display Certificate info":
      key: "c"
      modifier: "shift"
      read_only: false
      helptext: "Attempt to display certificate information"
      widget: "command"
      widget_args:
        command: ["openssl", "x509", "-text", "-noout"]
        _pass_selected_obj: true
        input_path: "data"
        wait_for_keypress: true
    "Export":
      key: "e"
      modifier: "shift"
      read_only: false
      helptext: "Export selected configmap to a file"
      widget: "inputbox"
      inputtitle: "Export to file:"
      confirm: "path_exists"
      confirmtitle: "File already exists; overwrite?:"
      action: "call"
      action_call: "export_data"
      action_args:
        _pass_result: true
        _pass_selected: true
        _pass_obj: true
        _extra_args:
          base_path: "data"
          name_attr: "data"
          raw_export: true
    "Decode and Export":
      key: "d"
      modifier: "shift"
      read_only: false
      helptext: "Decode and export selected configmap to a file"
      widget: "inputbox"
      inputtitle: "Decode and Export to file:"
      confirm: "path_exists"
      confirmtitle: "File already exists; overwrite?:"
      action: "call"
      action_call: "export_data"
      action_args:
        _pass_result: true
        _pass_selected: true
        _pass_obj: true
        _extra_args:
          base_path: "data"
          name_attr: "data"
