kind: "Config"
api_family: "operator.openshift.io"
default_command: "configs.operator.openshift.io"
command:
- "configs.operator"
- "config.operator"
listview:
  name: "Configs (Operator)"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "Config Info (Operator)"
  infopad:
    row_indexes:
      Normal:
        fields: ["cluster_version", "loglevel", "operator_loglevel", "management_state", "ready_replicas"]
    rows:
      cluster_version:
        header: [["Cluster ", ["main", "infoheader"]], ["V", ["main", "infoheader_shortcut"]], ["ersion:", ["main", "infoheader"]]]
        paths:
        - path: "metadata#ownerReferences"
          pathtype: "items"
          subpaths:
          - "name"
          when:
          - key: "kind"
            eq: "ClusterVersion"
        default: "<none>"
      loglevel:
        header: [["Loglevel:", ["main", "infoheader"]]]
        path: "spec#logLevel"
        type: "str"
      management_state:
        header: [["Management State:", ["main", "infoheader"]]]
        path: "spec#managementState"
        type: "str"
      operator_loglevel:
        header: [["Operator Loglevel:", ["main", "infoheader"]]]
        path: "spec#operatorLogLevel"
        type: "str"
      ready_replicas:
        header: [["Ready Replicas:", ["main", "infoheader"]]]
        path: "status#readyReplicas"
        type: "int"
        formatting:
          field_colors:
          - type: "numerical"
  shortcuts:
    "Cluster Version":
      key: "v"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Cluster Version"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        owner_reference_path: "metadata#ownerReferences"
        kind: "ClusterVersion"
        api_family: "config.openshift.io"
