kind: ConfigMap
default_command: configmaps
command:
- cm
listview:
  name: Config Maps
  group: Core
  field_indexes:
    Normal: [namespace, name, data, immutable, age]
  sortcolumn: namespace
  fields:
    data:
      header: "# of Data:"
      path: "data"
      type: len
      formatting:
        field_colors:
        - type: numerical
      align: right
    immutable:
      header: "Immutable:"
      paths:
      - path: "immutable"
        pathtype: value
        type: bool
        default: ""
