kind: ConfigMap
default_command: configmaps
command:
- cm
listview:
  name: Config Maps
  group: Core
  field_indexes:
    Normal: [namespace, name, data, immutable, age]
  sortcolumn: namespace
  fields:
    data:
      header: "# of Data:"
      path: "data"
      type: len
      formatting:
        field_colors:
        - type: numerical
      align: right
    immutable:
      header: "Immutable:"
      paths:
      - path: "immutable"
        pathtype: value
        type: bool
        default: ""
infoview:
  name: Config Map Info
  listpad:
    on_activation:
      call: resourceinfodispatch
      kind: __ResourceView
      formatter: identify
      formatter_path: formatter
      obj_path: data
      title_path: configmap
    listgetter: listgetter_configmap_data
    infogetter: generic_infogetter
    field_indexes:
      Normal: [data, type]
    sortcolumn: data
    fields:
      data:
        header: "Data:"
        path: configmap
        type: str
      type:
        header: "Type:"
        path: type
        type: str
