kind: ConfigMap
default_command: configmaps
command:
- cm
listview:
  name: Config Maps
  group: Core
  field_indexes:
    Normal: [namespace, name, data, immutable, age]
  fields:
    data:
      header: "# of Data:"
      paths:
      - path: "data"
        type: len
      align: right
    immutable:
      header: "Immutable:"
      paths:
      - path: "immutable"
        pathtype: value
        type: bool
        default: ""
  sortcolumn: namespace
