kind: ConfigMap
default_command: configmaps
command:
- cm
listview:
  name: Config Maps
  group: Core
  fields:
  - namespace
  - name
  - name: data
    header: "# of Data:"
    paths:
    - path: "data"
      type: len
    align: right
  - name: immutable
    header: "Immutable:"
    paths:
    - path: "immutable"
      pathtype: value
      type: bool
  - age
  sortcolumn: namespace
