---
kind: "Config"
api_family: "samples.operator.openshift.io"
default_command: "configs.samples.operator.openshift.io"
command:
  - "config.samples"
listview:
  name: "Configs"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "Config Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["configuration_header", "configuration_architectures",
                 "configuration_management_state",
                 "configuration_samples_registry",
                 "configuration_skipped_image_streams",
                 "configuration_skipped_templates", "status_header",
                 "status_architectures", "status_management_state",
                 "status_samples_registry", "status_skipped_image_streams",
                 "status_skipped_templates", "status_version"]
    rows:
      configuration_architectures:
        header: [["  Architectures:", ["main", "infoheader"]]]
        path: "spec#architectures"
        type: "raw"
        formatter: "list"
      configuration_header:
        header: [["Configuration:", ["main", "infoheader"]]]
      configuration_management_state:
        header: [["  Management State:", ["main", "infoheader"]]]
        path: "spec#managementState"
        type: "str"
      configuration_samples_registry:
        header: [["  Samples Registry:", ["main", "infoheader"]]]
        path: "spec#samplesRegistry"
        type: "str"
      configuration_skipped_image_streams:
        header: [["  Skipped Image Streams:", ["main", "infoheader"]]]
        path: "spec#skippedImagestreams"
        type: "raw"
        formatter: "list"
      configuration_skipped_templates:
        header: [["  Skipped Templates:", ["main", "infoheader"]]]
        path: "spec#skippedTemplates"
        type: "raw"
        formatter: "list"
      status_architectures:
        header: [["  Architectures:", ["main", "infoheader"]]]
        path: "status#architectures"
        type: "raw"
        formatter: "list"
      status_header:
        header: [["Status:", ["main", "infoheader"]]]
      status_management_state:
        header: [["  Management State:", ["main", "infoheader"]]]
        path: "status#managementState"
        type: "str"
      status_samples_registry:
        header: [["  Samples Registry:", ["main", "infoheader"]]]
        path: "status#samplesRegistry"
        type: "str"
      status_skipped_image_streams:
        header: [["  Skipped Image Streams:", ["main", "infoheader"]]]
        path: "status#skippedImagestreams"
        type: "raw"
        formatter: "list"
      status_skipped_templates:
        header: [["  Skipped Templates:", ["main", "infoheader"]]]
        path: "status#skippedTemplates"
        type: "raw"
        formatter: "list"
      status_version:
        header: [["  Version:", ["main", "infoheader"]]]
        path: "status#version"
        type: "str"
