---
kind: "ConfigMap"
default_command: "configmaps"
command:
- "cm"
listview:
  name: "Config Maps"
  group: "Core"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "data", "immutable", "age"]
      sortcolumn: "namespace"
  fields:
    data:
      header: "# of Data:"
      path: "data"
      type: "len"
      formatting:
        field_colors:
        - type: "numerical"
      align: "right"
    immutable:
      header: "Immutable:"
      paths:
      - path: "immutable"
        pathtype: "value"
        type: "bool"
        default: ""
  actions:
    actionlist:
      "Delete resource":
        description: "Delete resource"
        category: "Resource Level"
        confirm: true
        actionfunc: "delete_resource"
infoview:
  name: "Config Map Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["controller", "immutable"]
    rows:
      controller:
        header: [["C", ["main", "infoheader_shortcut"]], ["ontroller:", ["main", "infoheader"]]]
        paths:
        - path: "metadata#ownerReferences"
          pathtype: "items"
          subpaths:
          - "kind"
          - "apiVersion"
          - "name"
          when:
          - key: "controller"
            eq: true
          type: ["kind", "api_group", "name"]
        default: "<none>"
        formatter: "list"
        formatting:
          field_colors:
          - type: "kind"
          - type: "api_group"
          - type: "generic"
          field_separators:
          - type: "kind_api_group"
          - type: "kind"
      immutable:
        header: [["Immutable:", ["main", "infoheader"]]]
        paths:
        - path: "immutable"
          pathtype: "value"
          type: "bool"
          default: "False"
  listpad:
    on_activation:
      call: "resourceinfodispatch"
      kind: "__ResourceView"
      formatter: "identify"
      formatter_path: "formatter"
      obj_path: "data"
      title_path: "configmap"
    listgetter: "listgetter_configmap_data"
    infogetter: "generic_infogetter"
    field_indexes:
      Normal:
        fields: ["data", "type"]
        sortcolumn: "data"
    fields:
      data:
        header: "Data:"
        path: "configmap"
        type: "str"
      type:
        header: "Type:"
        path: "type"
        type: "str"
  shortcuts:
    "Attempt to display Certificate info":
      key: "d"
      modifier: "shift"
      read_only: true
      helptext: "Attempt to display certificate information"
      widget: "command"
      widget_args:
        command: ["openssl", "x509", "-text", "-noout"]
        _pass_selected_obj: true
        input_path: "data"
        wait_for_keypress: true
    "Export":
      key: "e"
      modifier: "shift"
      read_only: false
      helptext: "Export selected configmap to a file"
      widget: "inputbox"
      inputtitle: "Export to file:"
      confirm: "path_exists"
      confirmtitle: "File already exists; overwrite?:"
      action: "call"
      action_call: "export_data"
      action_args:
        _pass_result: true
        _pass_selected: true
        _pass_obj: true
        _extra_args:
          base_path: "data"
          name_attr: "data"
          raw_export: true
    "Decode and Export":
      key: "x"
      modifier: "shift"
      read_only: false
      helptext: "Decode and export selected configmap to a file"
      widget: "inputbox"
      inputtitle: "Decode and Export to file:"
      confirm: "path_exists"
      confirmtitle: "File already exists; overwrite?:"
      action: "call"
      action_call: "export_data"
      action_args:
        _pass_result: true
        _pass_selected: true
        _pass_obj: true
        _extra_args:
          base_path: "data"
          name_attr: "data"
    "List Pods using this ConfigMap":
      key: "p"
      modifier: "shift"
      read_only: true
      helptext: "List Pods using this ConfigMap (if any)"
      widget: "windowwidget"
      title: "Pods:"
      headers: ["Namespace:", "Name:"]
      # This isn't supported for now
      sortcolumn: "name"
      itemgetter: "get_pod_configmaps"
      itemgetter_args:
        cm_namespace: ["metadata#namespace"]
        cm_name: ["metadata#name"]
        pod_name: ""
      selectable: true
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        kind: "Pod"
        name_path: 1
        namespace_path: 0
    "Open controller":
      key: "c"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for controller"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        namespace_path: "metadata#namespace"
        owner_reference_path: "metadata#ownerReferences"
