kind: Config
api_family: imageregistry.operator.openshift.io
default_command: configs.imageregistry.operator.openshift.io
listview:
  name: Configs (Imageregistry Operator)
  group: OpenShift
  field_indexes:
    Normal: [name, age]
