kind: Console
api_family: config.openshift.io
default_command: consoles.config.openshift.io
command:
- consoles.config
- console.config
listview:
  name: Consoles (Config)
  group: OpenShift
  field_indexes:
    Normal: [name, age]
