kind: "ControllerConfig"
api_family: "machineconfiguration.openshift.io"
default_command: "controllerconfigs"
listview:
  name: "Controller Configs"
  group: "OpenShift"
  field_indexes:
    Normal: ["name", "age"]
