kind: "ContainerRuntimeConfig"
api_family: "machineconfiguration.openshift.io"
default_command: "containerruntimeconfigs"
listview:
  name: "Container Runtime Configs"
  group: "OpenShift"
  field_indexes:
    Normal: ["name", "age"]
