kind: "Deployment"
api_family: "apps"
default_command: "deployments"
command:
- "deploy"
- "dep"
listview:
  name: "Deployments"
  group: "Workloads"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "desired_replicas", "current_replicas", "ready_replicas", "uptodate_replicas", "available_replicas", "unavailable_replicas", "age"]
      sortcolumn: "namespace"
  fields:
    available_replicas:
      header: "Available:"
      paths:
      - path: ["status#availableReplicas", "status#replicas"]
        pathtype: "comparison"
        default: [0, 0]
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
          - min: 0
            max: 1
            field_colors:
            - context: "main"
              type: "status_ok"
          - default: true
            field_colors:
            - context: "main"
              type: "status_pending"
      align: "right"
    current_replicas:
      header: "Current:"
      paths:
      - path: ["status#replicas", "spec#replicas"]
        pathtype: "comparison"
        default: [0, 0]
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
          - min: 0
            max: 1
            field_colors:
            - context: "main"
              type: "status_ok"
          - default: true
            field_colors:
            - context: "main"
              type: "status_not_ok"
      align: "right"
    desired_replicas:
      header: "Desired:"
      path: "spec#replicas"
      default: 0
      type: "int"
      formatting:
        field_colors:
        - type: "numerical"
      align: "right"
    ready_replicas:
      header: "Ready:"
      paths:
      - path: ["status#readyReplicas", "status#replicas"]
        pathtype: "comparison"
        default: [0, 0]
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
          - min: 0
            max: 1
            field_colors:
            - context: "main"
              type: "status_ok"
          - min: -1
            max: 0
            field_colors:
            - context: "main"
              type: "status_pending"
          - default: true
            field_colors:
            - context: "main"
              type: "status_not_ok"
      align: "right"
    unavailable_replicas:
      header: "Unavailable:"
      path: "status#unavailableReplicas"
      default: 0
      type: "raw"
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
          - min: 0
            max: 1
            field_colors:
            - context: "main"
              type: "status_ok"
          - default: true
            field_colors:
            - context: "main"
              type: "status_not_ok"
      align: "right"
    uptodate_replicas:
      header: "Up to Date:"
      paths:
      - path: ["status#updatedReplicas", "status#replicas"]
        pathtype: "comparison"
        default: [0, 0]
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
          - min: 0
            max: 1
            field_colors:
            - context: "main"
              type: "status_ok"
          - default: true
            field_colors:
            - context: "main"
              type: "status_pending"
      align: "right"
  actions:
    actionlist:
      "Delete resource":
        description: "Delete resource"
        category: "Resource Level"
        confirm: true
        actionfunc: "delete_resource"
      "Rescale resource":
        description: "Rescale resource"
        category: "Resource Level"
        confirm: true
        actionfunc: "rescale_resource"
        query: "New scale"
        queryval: "scale"
        queryfunc: "string"
      "Pause resource (Rollout)":
        description: "Pause resource"
        category: "Resource Level"
        metadata: [["Strategy: Rollout", ["windowwidget", "description"]]]
        confirm: true
        actionfunc: "pause_resource_rollout"
      "Resume resource (Rollout)":
        description: "Resume resource"
        category: "Resource Level"
        metadata: [["Strategy: Rollout", ["windowwidget", "description"]]]
        confirm: true
        actionfunc: "resume_resource_rollout"
      "Restart resource (Rollout)":
        description: "Restart resource"
        category: "Resource Level"
        metadata: [["Strategy: Rollout", ["windowwidget", "description"]]]
        confirm: true
        actionfunc: "restart_resource_rollout"
      "Restart resource (Rescale)":
        description: "Restart resource"
        category: "Deprecated"
        metadata: [["Strategy: Rescale", ["windowwidget", "description"]]]
        confirm: true
        actionfunc: "restart_resource_rescale"
      "Stop resource (Rescale)":
        description: "Stop resource"
        category: "Deprecated"
        metadata: [["Strategy: Rescale", ["windowwidget", "description"]]]
        confirm: true
        actionfunc: "stop_resource_rescale"
infoview:
  name: "Deployment Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["label_selector", "set_based_selector", "node_selector", "priority_class", "update_strategy", "replicas", "available"]
    rows:
      available:
        header: [["Available:", ["main", "infoheader"]]]
        paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
          - key: "type"
            eq: "Available"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                - context: "main"
                  type: "status_ok"
              "False":
                field_colors:
                - context: "main"
                  type: "status_not_ok"
      label_selector:
        header: [["Label Selector:", ["main", "infoheader"]]]
        paths:
        - path: ["spec#selector#matchLabels"]
          pathtype: "key_value"
          default: ["<none>"]
        formatter: "list"
        formatting:
          field_colors:
          - type: "key"
          - type: "value"
          field_separators:
          - type: "selector"
      node_selector:
        header: [["Node Selector:", ["main", "infoheader"]]]
        paths:
        - path: ["spec#template#spec#nodeSelector"]
          pathtype: "key_value"
          default: ["<none>"]
        formatter: "list"
        formatting:
          field_colors:
          - type: "key"
          - type: "value"
          field_separators:
          - type: "selector"
      priority_class:
        header: [["P", ["main", "infoheader_shortcut"]], ["riority Class:", ["main", "infoheader"]]]
        path: "spec#template#spec#priorityClassName"
        type: "str"
      replicas:
        header: [["Replicas:", ["main", "infoheader"]]]
        paths:
        - path: [["spec#replicas"], " Desired", ["status#replicas"], " Current", ["status#readyReplicas"], " Ready", ["status#updatedReplicas"], " Up to Date", ["status#unavailableReplicas"], " Unavailable"]
          pathtype: "tuple"
          default: [0, "", 0, "", 0, "", 0, "", 0, ""]
        formatter: "list"
        formatting:
          field_colors:
          - type: "numerical"
          - type: "generic"
          - type: "numerical"
          - type: "generic"
          - type: "numerical"
          - type: "generic"
          - type: "numerical"
          - type: "generic"
          - type: "numerical"
          - type: "generic"
          - type: "numerical"
          - type: "generic"
          field_separators:
          - type: "no_pad"
          - type: "fraction_spaced"
          - type: "no_pad"
          - type: "fraction_spaced"
          - type: "no_pad"
          - type: "fraction_spaced"
          - type: "no_pad"
          - type: "fraction_spaced"
          - type: "no_pad"
          - type: "fraction_spaced"
          - type: "no_pad"
      set_based_selector:
        header: [["Set-based Selector:", ["main", "infoheader"]]]
        paths:
        - path: "spec#selector#matchExpressions"
          pathtype: "match_expression"
          default: "<none>"
        formatter: "list"
        formatting:
          field_colors:
          - type: "key"
          - type: "operator"
          - type: "value"
          field_separators:
          - type: "space"
          - type: "no_pad"
      update_strategy:
        header: [["Update Strategy:", ["main", "infoheader"]]]
        paths:
        - path: [["spec#strategy#type"], " (", "Max Surge: ", ["spec#strategy#rollingUpdate#maxSurge"], "Max Unavailable: ", ["spec#strategy#rollingUpdate#maxUnavailable"], ")"]
          pathtype: "tuple"
          when:
          - key: "spec#strategy#type"
            eq: "RollingUpdate"
        - path: [["spec#strategy#type"]]
          pathtype: "tuple"
          when:
          - key: "spec#strategy#type"
            eq: "Recreate"
        formatter: "list"
        formatting:
          field_colors:
          - type: "generic"
          - type: "generic"
          - context: "main"
            type: "infoheader"
          # Ideally we want to achieve numerical with unit here
          - type: "numerical"
          - context: "main"
            type: "infoheader"
          # Ideally we want to achieve numerical with unit here
          - type: "numerical"
          - type: "generic"
          field_separators:
          - type: "no_pad"
          - type: "no_pad"
          - type: "no_pad"
          - type: "list"
          - type: "no_pad"
          - type: "no_pad"
  listpad:
    listgetter: "generic_listgetter"
    listgetter_args:
      _kind: "Pod"
      _label_selector_path: "spec#selector#matchLabels"
    infogetter: "generic_infogetter"
    on_activation:
      call: "resourceinfodispatch"
      kind: "Pod"
    field_indexes:
      Wide:
        fields: ["namespace", "name", "controller", "pod_status", "node_name", "pod_ip", "age", "restarts", "last_restart", "containers"]
        sortcolumn: "pod_status"
      Normal:
        fields: ["namespace", "name", "controller", "pod_status", "node_name", "age", "restarts", "last_restart"]
        sortcolumn: "pod_status"
      Compact:
        fields: ["namespace", "name", "pod_status", "age", "restarts", "last_restart"]
        sortcolumn: "pod_status"
    fields:
      containers:
        header: "Containers:"
        paths:
        - paths:
          - "spec#initContainers"
          - "spec#containers"
          pathtype: "items"
          subpaths:
          - "name"
          - subpath: "image"
            regex: ["^.+/[^:^/]+:(.+?)@.*", "^.+/[^:^/]+:(.+)"]
          type: "raw"
        formatter: "list"
        formatting:
          field_colors:
          - type: "generic"
          - type: "version"
          field_separators:
          - type: "version"
      controller:
        header: "Controller:"
        paths:
        - path: "metadata#ownerReferences"
          pathtype: "items"
          subpaths:
          - "kind"
          - "apiVersion"
          - "name"
          when:
          - key: "controller"
            eq: true
          type: ["kind", "api_group", "name"]
        formatter: "list"
        formatting:
          field_colors:
          - type: "kind"
          - type: "api_group"
          - type: "generic"
          field_separators:
          - type: "kind_api_group"
          - type: "kind"
      last_restart:
        header: "Latest Restart:"
        paths:
        - path: "status#containerStatuses"
          pathtype: "items"
          subpath: ["state#running#startedAt", "lastState#terminated#finishedAt"]
          when:
          - key: "restartCount"
            gt: 0
          action: "latest"
          type: "timestamp"
        default: -1
        formatter: "age"
        align: "right"
      node_name:
        header: "Node:"
        path: "spec#nodeName"
        type: "host"
        default: "<none>"
        formatting:
          field_colors:
          - type: "host"
      pod_ip:
        header: "Pod IP:"
        path: "status#podIP"
        default: "<unset>"
        type: "address"
        formatter: "address"
      restarts:
        header: "Restarts:"
        paths:
        - path: "status#containerStatuses"
          pathtype: "items"
          subpath: "restartCount"
          action: "sum"
          type: "int"
        formatting:
          field_colors:
          - type: "numerical"
        align: "right"
        default: 0
  shortcuts:
    "Priority Class":
      key: "p"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Priority Class"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        kind: "PriorityClass"
        api_family: "scheduling.k8s.io"
        name_path: "spec#template#spec#priorityClassName"
    "Pod template":
      key: "t"
      modifier: "shift"
      read_only: true
      helptext: "Show Pod template"
      action: "call"
      action_call: "view_yaml"
      action_args:
        title: "Pod template"
        _pass_obj: true
        path: "spec#template"
