kind: Deployment
api_family: apps
default_command: deployments
command:
- deploy
- dep
listview:
  name: Deployments
  group: Workloads
  field_indexes:
    Normal: [namespace, name, ready_replicas_tuple, uptodate_replicas, available_replicas, age, status_deployment, status_message_deployment]
  sortcolumn: namespace
  actions:
    actionlist:
      #"Delete resource":
      #  description: Delete resource
      #  confirm: true
      #  actionfunc: delete_resource
      "Rescale resource":
        description: Rescale resource
        category: Resource Level
        confirm: true
        actionfunc: rescale_resource
        query: New scale
        queryval: scale
        queryfunc: string
      "Pause resource (Rollout)":
        description: Pause resource
        category: Resource Level
        metadata: [["Strategy: Rollout", ["windowwidget", "description"]]]
        confirm: true
        actionfunc: pause_resource_rollout
      "Resume resource (Rollout)":
        description: Resume resource
        category: Resource Level
        metadata: [["Strategy: Rollout", ["windowwidget", "description"]]]
        confirm: true
        actionfunc: resume_resource_rollout
      "Restart resource (Rollout)":
        description: Restart resource
        category: Resource Level
        metadata: [["Strategy: Rollout", ["windowwidget", "description"]]]
        confirm: true
        actionfunc: restart_resource_rollout
      "Restart resource (Rescale)":
        description: Restart resource
        category: Deprecated
        metadata: [["Strategy: Rescale", ["windowwidget", "description"]]]
        confirm: true
        actionfunc: restart_resource_rescale
      "Stop resource (Rescale)":
        description: Stop resource
        category: Deprecated
        metadata: [["Strategy: Rescale", ["windowwidget", "description"]]]
        confirm: true
        actionfunc: stop_resource_rescale
