kind: DNS
api_family: config.openshift.io
default_command: dnses.config.openshift.io
command:
- dnses.config
- dns.config
listview:
  name: DNSes (Config)
  group: OpenShift
  field_indexes:
    Normal: [name, age]
