---
kind: "DNS"
api_family: "config.openshift.io"
default_command: "dnses.config.openshift.io"
command:
  - "dnses.config"
  - "dns.config"
listview:
  name: "DNSes"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "DNS Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["base_domain"]
    rows:
      base_domain:
        header: [["Base Domain:", ["main", "infoheader"]]]
        path: "spec#baseDomain"
        type: "str"
