kind: FeatureGate
api_family: config.openshift.io
default_command: featuregates.config.openshift.io
command:
- featuregates.config
- featuregate.config
listview:
  name: Feature Gates (Config)
  group: OpenShift
  field_indexes:
    Normal: [name, age]
