kind: "FelixConfiguration"
api_family: "crd.projectcalico.org"
default_command: "felixconfigurations"
command:
- "felixconfs"
- "felixconf"
listview:
  name: "Felix Configurations"
  group: "Calico"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "Felix Configuration Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["bpf_header", "bpf_enabled", "bpf_connect_time_load_balancing", "bpf_host_networked_nat_without_ctlb", "bpf_log_level", "log_severity_screen", "health_port", "floating_ips", "reporting_interval", "ipip_enabled", "vxlan_enabled", "vxlan_vni"]
    rows:
      bpf_connect_time_load_balancing:
        header: [["  Connect Time Load Balancing:", ["main", "infoheader"]]]
        path: "spec#bpfConnectTimeLoadBalancing"
        type: "str"
      bpf_enabled:
        header: [["  Enabled:", ["main", "infoheader"]]]
        path: "spec#bpfEnabled"
        type: "str"
      bpf_header:
        header: [["BPF:", ["main", "infoheader"]]]
      bpf_host_networked_nat_without_ctlb:
        header: [["  Host Networked NAT Without Connect Time Load Balancing:", ["main", "infoheader"]]]
        path: "spec#bpfHostNetworkedNATWithoutCTLB"
        type: "str"
      bpf_log_level:
        header: [["  Log Level:", ["main", "infoheader"]]]
        path: "spec#bpfLogLevel"
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            substitutions:
              "": "Off"
      floating_ips:
        header: [["Floating IPs:", ["main", "infoheader"]]]
        path: "spec#floatingIPs"
        type: "bool"
      health_port:
        header: [["Health Port:", ["main", "infoheader"]]]
        path: "spec#healthPort"
        default: "<unset>"
        type: "int"
        formatting:
          field_colors:
          - type: "numerical"
      log_severity_screen:
        header: [["Log Severity Screen:", ["main", "infoheader"]]]
        path: "spec#logSeverityScreen"
        type: "str"
      ipip_enabled:
        header: [["IPIP Enabled:", ["main", "infoheader"]]]
        path: "spec#ipipEnabled"
        default: false
        type: "bool"
      reporting_interval:
        header: [["Reporting Interval:", ["main", "infoheader"]]]
        path: "spec#reportingInterval"
        type: "raw"
        formatter: "numerical_with_units"
      vxlan_enabled:
        header: [["VXLAN Enabled:", ["main", "infoheader"]]]
        path: "spec#vxlanEnabled"
        default: false
        type: "bool"
      vxlan_vni:
        header: [["VXLAN VNI:", ["main", "infoheader"]]]
        path: "spec#vxlanVNI"
        default: "<unset>"
        type: "int"
        formatting:
          field_colors:
          - type: "numerical"
