kind: FelixConfiguration
api_family: crd.projectcalico.org
default_command: felixconfigurations
command:
- felixconfs
- felixconf
listview:
  name: Felix Configurations
  group: CNI
  field_indexes:
    Normal: [name, age]
