kind: HelmChartConfig
api_family: helm.cattle.io
default_command: helmchartconfigs
listview:
  name: Helmchart Configs
  group: API & Extendability
  field_indexes:
    Normal: [namespace, name, age]
  sortcolumn: namespace
