kind: "HostFirmwareSettings"
api_family: "metal3.io"
default_command: "hostfirmwaresettings"
listview:
  name: "Host Firmware Settings"
  group: "Provisioning"
  field_indexes:
    Normal: ["namespace", "name", "age"]
  sortcolumn: "namespace"
