kind: "ImageContentPolicy"
api_family: "config.openshift.io"
default_command: "imagecontentpolicies.config.openshift.io"
command:
- "imagecontentpolicies.config"
- "imagecontentpolicy.config"
listview:
  name: "Image Content Policies (Config)"
  group: "OpenShift"
  field_indexes:
    Normal: ["name", "age"]
