kind: Image
api_family: config.openshift.io
default_command: images.config.openshift.io
command:
- image.config.openshift.io
- images.config.os
- image.config.os
- osconfimages
- osconfimage
- osconfimg
listview:
  name: Images (OpenShift Config)
  group: Caching
  field_indexes:
    Normal: [name, age]
