kind: Image
api_family: config.openshift.io
default_command: images.config.openshift.io
command:
- image.config.openshift.io
- images.config
- image.config
- osconfimages
- osconfimage
- osconfimg
listview:
  name: Images (Config)
  group: OpenShift
  field_indexes:
    Normal: [name, age]
