kind: ImageContentPolicy
api_family: config.openshift.io
default_command: imagecontentpolicies.config.openshift.io
listview:
  name: Image Content Policies
  group: OpenShift
  field_indexes:
    Normal: [name, age]
