---
kind: "Image"
api_family: "config.openshift.io"
default_command: "images.config.openshift.io"
command:
  - "image.config.openshift.io"
  - "images.config"
  - "image.config"
  - "osconfimages"
  - "osconfimage"
  - "osconfimg"
listview:
  name: "Images"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "Image Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["cluster_version", "additional_trusted_ca", "internal_registry_hostname", "external_registry_hostnames"]
    rows:
      additional_trusted_ca:
        header: [["Additional Trusted CA:", ["main", "infoheader"]]]
        path: "spec#additionalTrustedCA#name"
        type: "str"
      cluster_version:
        header: [["Cluster ", ["main", "infoheader"]], ["V", ["main", "infoheader_shortcut"]], ["ersion:", ["main", "infoheader"]]]
        paths:
          - path: "metadata#ownerReferences"
            pathtype: "items"
            subpaths:
              - "name"
            when:
              - key: "kind"
                eq: "ClusterVersion"
        default: "<none>"
      external_registry_hostnames:
        header: [["External Registry Hostnames:", ["main", "infoheader"]]]
        path: "status#externalRegistryHostnames"
        type: "raw"
        formatter: "list"
      internal_registry_hostname:
        header: [["Internal Registry Hostname:", ["main", "infoheader"]]]
        path: "status#internalRegistryHostname"
        type: "str"
  shortcuts:
    "Cluster Version":
      key: "v"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Cluster Version"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        owner_reference_path: "metadata#ownerReferences"
        kind: "ClusterVersion"
        api_family: "config.openshift.io"
