---
kind: "ImageContentPolicy"
api_family: "config.openshift.io"
default_command: "imagecontentpolicies.config.openshift.io"
command:
  - "imagecontentpolicies.config"
  - "imagecontentpolicy.config"
listview:
  name: "Image Content Policies"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
