kind: Infrastructure
api_family: config.openshift.io
default_command: infrastructures.config.openshift.io
listview:
  name: Infrastructures
  group: OpenShift
  field_indexes:
    Normal: [name, age]
