kind: "Infrastructure"
api_family: "config.openshift.io"
default_command: "infrastructures.config.openshift.io"
command:
- "infrastructures.config"
- "infrastructure.config"
listview:
  name: "Infrastructures (Config)"
  group: "OpenShift"
  field_indexes:
    Normal: ["name", "age"]
