---
kind: "IngressRouteTCP"
api_family: "traefik.io"
default_command: "ingressroutetcps"
command:
  - "ingroutetcps"
  - "ingroutetcp"
listview:
  name: "Ingress Route TCPs"
  group: "Network"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
infoview:
  name: "Ingress Route TCP Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["entry_points"]
    rows:
      entry_points:
        header: [["Entry Points:", ["main", "infoheader"]]]
        path: "spec#entryPoints"
        type: "raw"
        formatter: "list"
  listpad:
    listgetter: "listgetter_path"
    listgetter_args:
      path: "spec#routes"
    infogetter: "generic_infogetter"
    field_indexes:
      Normal:
        fields: ["match", "services"]
        sortcolumn: "match"
    fields:
      match:
        header: "Match:"
        path: "match"
        type: "str"
      services:
        header: "Services:"
        paths:
          - path: "services"
            pathtype: "items"
            subpaths:
              - "name"
              - "port"
              - "serversTransport"
        formatter: "list"
        formatting:
          field_colors:
            - type: "service"
            - type: "port"
            - type: "generic"
          field_separators:
            - type: "port"
            - type: "service"
