kind: "IngressRoute"
api_family: "traefik.io"
default_command: "ingressroutes"
command:
- "ingroutes"
- "ingroute"
listview:
  name: "Ingress Routes"
  group: "Network"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
