kind: "IngressRouteTCP"
api_family: "traefik.io"
default_command: "ingressroutetcps"
command:
- "ingroutetcps"
- "ingroutetcp"
listview:
  name: "Ingress Route TCPs"
  group: "Network"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
