kind: "IngressRouteUDP"
api_family: "traefik.containo.us"
default_command: "ingressroutetcps"
listview:
  name: "Ingress Route UDPs (Old API)"
  group: "Network"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
