---
kind: "IngressRouteTCP"
api_family: "traefik.io"
default_command: "ingressroutetcps"
command:
  - "ingroutetcps"
  - "ingroutetcp"
listview:
  name: "Ingress Route TCPs"
  group: "Network"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "entrypoints", "age"]
      sortcolumn: "namespace"
  fields:
    entrypoints:
      header: "Entrypoints:"
      path: "spec#entryPoints"
      default: ["<none>"]
      type: "raw"
      formatter: "list"
infoview:
  name: "Ingress Route TCP Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["entry_points", "tls_header", "tls_cert_resolver",
                 "tls_secret_name", "tls_options_header",
                 "tls_options_name", "tls_options_namespace",
                 "tls_domains"]
    rows:
      entry_points:
        header: [["Entry Points:", ["main", "infoheader"]]]
        path: "spec#entryPoints"
        type: "raw"
        formatter: "list"
      tls_cert_resolver:
        header: [["  Cert Resolver:", ["main", "infoheader"]]]
        path: "spec#tls#certResolver"
        type: "str"
      tls_domains:
        header: [["  Domains:", ["main", "infoheader"]]]
        paths:
          - path: "spec#tls#domains"
            pathtype: "key_value"
        formatter: "list"
        formatting:
          field_colors:
            - type: "key"
            - type: "value"
          field_separators:
            - type: "keyvalue"
      tls_header:
        header: [["TLS:", ["main", "infoheader"]]]
      tls_options_header:
        header: [["  ", ["main", "infoheader"]],
                 ["O", ["main", "infoheader_shortcut"]],
                 ["ptions:", ["main", "infoheader"]]]
      tls_options_name:
        header: [["    Name:", ["main", "infoheader"]]]
        path: "spec#tls#options#name"
        default: "<none>"
        type: "str"
      tls_options_namespace:
        header: [["    Name", ["main", "infoheader"]],
                 ["s", ["main", "infoheader_shortcut"]],
                 ["pace:", ["main", "infoheader"]]]
        path: "spec#tls#options#namespace"
        default: "<none>"
        type: "str"
      tls_secret_name:
        header: [["  ", ["main", "infoheader"]],
                 ["S", ["main", "infoheader_shortcut"]],
                 ["ecret Name:", ["main", "infoheader"]]]
        path: "spec#tls#secretName"
        default: "<none>"
        type: "str"
  listpad:
    on_activation:
      call: "resourceinfodispatch"
      kind: "__IngressRouteTCPEntry"
      api_family: "traefik.io"
    listgetter: "listgetter_path"
    listgetter_args:
      path: "spec#routes"
    infogetter: "generic_infogetter"
    infogetter_args:
      _extra_data:
        namespace: ["metadata#namespace"]
    field_indexes:
      Normal:
        fields: ["match", "services"]
        sortcolumn: "match"
    fields:
      match:
        header: "Match:"
        path: "match"
        type: "str"
      services:
        header: "Services:"
        paths:
          - path: "services"
            pathtype: "items"
            subpaths:
              - "name"
              - "port"
              - "serversTransport"
        formatter: "list"
        formatting:
          field_colors:
            - type: "service"
            - type: "port"
            - type: "generic"
          field_separators:
            - type: "port"
            - type: "service"
  shortcuts:
    "TLS Options":
      key: "o"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for TLS Options"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        kind: "TLSOption"
        api_family: "traefik.io"
        name_path: "spec#tls#options#name"
        namespace_path: "spec#tls#options#namespace"
    "TLS Options Namespace":
      key: "s"
      read_only: true
      helptext: "Open info page for TLS options Namespace"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        kind: "Namespace"
        name_path: "spec#tls#options#namespace"
    "TLS Store":
      key: "t"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for TLS Store"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        kind: "TLSStore"
        api_family: "traefik.io"
        name: "default"
        namespace_path: "metadata#namespace"
    "Secret":
      key: "s"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Secret"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        kind: "Secret"
        name_path: "spec#tls#secretName"
        namespace_path: "metadata#namespace"
