kind: "IngressRouteUDP"
api_family: "traefik.containo.us"
default_command: "ingressroutetcps"
command:
- "ingrouteudps"
- "ingrouteudp"
listview:
  name: "Ingress Route UDPs"
  group: "Network"
  field_indexes:
    Normal: ["namespace", "name", "age"]
  sortcolumn: "namespace"
