kind: "IngressRoute"
api_family: "traefik.containo.us"
default_command: "ingressroutes"
command:
- "ingroutes"
- "ingroute"
listview:
  name: "Ingress Routes"
  group: "Network"
  field_indexes:
    Normal: ["namespace", "name", "age"]
  sortcolumn: "namespace"
