kind: IngressController
api_family: operator.openshift.io
default_command: ingresscontrollers
listview:
  name: Ingress Controllers
  group: OpenShift
  field_indexes:
    Normal: [namespace, name, age]
  sortcolumn: namespace
