kind: "IngressRouteUDP"
api_family: "traefik.io"
default_command: "ingressroutetcps"
command:
- "ingrouteudps"
- "ingrouteudp"
listview:
  name: "Ingress Route UDPs"
  group: "Network"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
