kind: KubeControllersConfiguration
api_family: crd.projectcalico.org
default_command: kubecontrollersconfigurations
command:
- kubectlconfs
- kubectlconf
listview:
  name: Kube Controllers Configurations
  group: CNI
  field_indexes:
    Normal: [name, age]
