---
kind: "MachineConfigPool"
api_family: "machineconfiguration.openshift.io"
default_command: "machineconfigpools"
listview:
  name: "Machine Config Pools"
  group: "OpenShift"
  field_indexes:
    Wide:
      fields: ["name", "config", "paused", "updated", "updating", "degraded", "machine_count", "ready_machine_count", "updated_machine_count", "degraded_machine_count", "age"]
    Normal:
      fields: ["name", "config", "paused", "updated", "updating", "degraded", "machine_count_short", "ready_machine_count_short", "updated_machine_count_short", "degraded_machine_count_short", "age"]
  fields:
    config:
      header: "Config:"
      path: "status#configuration#name"
      type: "str"
    degraded:
      header: "Degraded:"
      paths:
        - path: "status#conditions"
          pathtype: "items"
          subpaths:
            - "status"
          when:
            - key: "type"
              eq: "Degraded"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
                - context: "main"
                  type: "status_not_ok"
            "False":
              field_colors:
                - context: "main"
                  type: "status_ok"
      type: "str"
    degraded_machine_count:
      header: "Degraded Machine Count:"
      path: "status#degradedMachineCount"
      type: "raw"
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
            - min: 0
              max: 1
              field_colors:
                - context: "types"
                  type: "watermark_low"
            - default: true
              field_colors:
                - context: "types"
                  type: "watermark_high"
      align: "right"
    degraded_machine_count_short:
      header: "Degraded Count:"
      path: "status#degradedMachineCount"
      type: "raw"
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
            - min: 0
              max: 1
              field_colors:
                - context: "types"
                  type: "watermark_low"
            - default: true
              field_colors:
                - context: "types"
                  type: "watermark_high"
      align: "right"
    machine_count:
      header: "Machine Count:"
      path: "status#machineCount"
      type: "int"
      formatting:
        field_colors:
          - type: "numerical"
      align: "right"
    machine_count_short:
      header: "Machines:"
      path: "status#machineCount"
      type: "int"
      formatting:
        field_colors:
          - type: "numerical"
      align: "right"
    paused:
      header: "Paused:"
      path: "spec#paused"
      type: "bool"
    ready_machine_count:
      header: "Ready Machine Count:"
      path: "status#readyMachineCount"
      type: "int"
      formatting:
        field_colors:
          - type: "numerical"
      align: "right"
    ready_machine_count_short:
      header: "Ready:"
      path: "status#readyMachineCount"
      type: "int"
      formatting:
        field_colors:
          - type: "numerical"
      align: "right"
    updated:
      header: "Updated:"
      paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
            - key: "type"
              eq: "Updated"
      type: "str"
    updated_machine_count:
      header: "Updated Machine Count:"
      path: "status#updatedMachineCount"
      type: "int"
      formatting:
        field_colors:
          - type: "numerical"
      align: "right"
    updated_machine_count_short:
      header: "Updated Count:"
      path: "status#updatedMachineCount"
      type: "int"
      formatting:
        field_colors:
          - type: "numerical"
      align: "right"
    updating:
      header: "Updating:"
      paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
            - key: "type"
              eq: "Updating"
      type: "str"
infoview:
  name: "Machine Config Pool Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["config", "machine_config_selector", "node_selector", "paused", "updated", "updating", "degraded", "machine_count", "ready_machine_count", "updated_machine_count", "degraded_machine_count"]
    rows:
      config:
        header: [["Config:", ["main", "infoheader"]]]
        path: "status#configuration#name"
        type: "str"
      degraded:
        header: [["Degraded:", ["main", "infoheader"]]]
        paths:
          - path: "status#conditions"
            pathtype: "items"
            subpaths:
              - "status"
            when:
              - key: "type"
                eq: "Degraded"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                  - context: "main"
                    type: "status_not_ok"
              "False":
                field_colors:
                  - context: "main"
                    type: "status_ok"
        type: "str"
      degraded_machine_count:
        header: [["Degraded Machine Count:", ["main", "infoheader"]]]
        path: "status#degradedMachineCount"
        type: "raw"
        formatter: "value_mapper"
        formatting:
          mapping:
            ranges:
              - min: 0
                max: 1
                field_colors:
                  - context: "types"
                    type: "watermark_low"
              - default: true
                field_colors:
                  - context: "types"
                    type: "watermark_high"
      machine_config_selector:
        header: [["Machine Config Selector:", ["main", "infoheader"]]]
        paths:
          - path: ["spec#machineConfigSelector#matchLabels"]
            pathtype: "key_value"
            default: ["<none>"]
        formatter: "list"
        formatting:
          field_colors:
            - type: "key"
            - type: "value"
          field_separators:
            - type: "selector"
      machine_count:
        header: [["Machine Count:", ["main", "infoheader"]]]
        path: "status#machineCount"
        type: "int"
        formatting:
          field_colors:
            - type: "numerical"
      node_selector:
        header: [["Node Selector:", ["main", "infoheader"]]]
        paths:
          - path: ["spec#nodeSelector#matchLabels"]
            pathtype: "key_value"
            default: ["<none>"]
        formatter: "list"
        formatting:
          field_colors:
            - type: "key"
            - type: "value"
          field_separators:
            - type: "selector"
      paused:
        header: [["Paused:", ["main", "infoheader"]]]
        path: "spec#paused"
        type: "bool"
      ready_machine_count:
        header: [["Ready Machine Count:", ["main", "infoheader"]]]
        path: "status#readyMachineCount"
        type: "int"
        formatting:
          field_colors:
            - type: "numerical"
      updated:
        header: [["Updated:", ["main", "infoheader"]]]
        paths:
          - path: "status#conditions"
            pathtype: "items"
            subpath: "status"
            when:
              - key: "type"
                eq: "Updated"
        type: "str"
      updated_machine_count:
        header: [["Updated Machine Count:", ["main", "infoheader"]]]
        path: "status#updatedMachineCount"
        type: "int"
        formatting:
          field_colors:
            - type: "numerical"
      updating:
        header: [["Updating:", ["main", "infoheader"]]]
        paths:
          - path: "status#conditions"
            pathtype: "items"
            subpath: "status"
            when:
              - key: "type"
                eq: "Updating"
        type: "str"
  shortcuts:
    "Show Machine Config list":
      key: "c"
      modifier: "shift"
      read_only: true
      helptext: "List Machine Configs"
      widget: "windowwidget"
      title: "Machine Configs:"
      headers: ["Name:", "Kind:", "API-version:"]
      selectable: true
      itemgetter: "get_list_fields"
      itemgetter_args:
        path: "spec#configuration#source"
        fields:
          - "name"
          - "kind"
          - "apiVersion"
      # Not supported for now
      sortcolumn: "name"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        name_path: 0
        kind_path: 1
        api_version_path: 2
