kind: "MachineConfigNode"
api_family: "machineconfiguration.openshift.io"
default_command: "machineconfignodes"
listview:
  name: "Machine Config Nodes"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "updated", "update_prepared", "update_executed", "update_postaction_complete", "update_complete", "resumed", "age"]
    Wide:
      fields: ["name", "updated", "update_prepared", "update_executed", "update_postaction_complete", "update_complete", "resumed", "update_compatible", "updated_files_and_os", "cordoned", "drained", "rebooted", "reloaded_crio", "age"]
  fields:
    cordoned:
      header: "Cordoned:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
        - key: "type"
          eq: "Cordoned"
        - key: "reason"
          ne: "NotYetOccured"
        default: ["<unset>"]
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
    drained:
      header: "Drained:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
        - key: "type"
          eq: "Drained"
        - key: "reason"
          ne: "NotYetOccured"
        default: ["<unset>"]
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
    rebooted:
      header: "Rebooted:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
        - key: "type"
          eq: "RebootedNode"
        - key: "reason"
          ne: "NotYetOccured"
        default: ["<unset>"]
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
    reloaded_crio:
      header: "Reloaded CRI-O:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
        - key: "type"
          eq: "ReloadedCRIO"
        - key: "reason"
          ne: "NotYetOccured"
        default: ["<unset>"]
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
    resumed:
      header: "Resumed:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
        - key: "type"
          eq: "Resumed"
        - key: "reason"
          ne: "NotYetOccured"
        default: ["<unset>"]
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_pending"
    update_compatible:
      header: "Update Compatible:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
        - key: "type"
          eq: "UpdateCompatible"
        - key: "reason"
          ne: "NotYetOccured"
        default: ["<unset>"]
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
    update_complete:
      header: "Update Complete:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
        - key: "type"
          eq: "UpdateComplete"
        - key: "reason"
          ne: "NotYetOccured"
        default: ["<unset>"]
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
    update_executed:
      header: "Update Executed:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
        - key: "type"
          eq: "UpdateExecuted"
        - key: "reason"
          ne: "NotYetOccured"
        default: ["<unset>"]
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
    updated:
      header: "Updated:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
        - key: "type"
          eq: "Updated"
        - key: "reason"
          ne: "NotYetOccured"
        default: ["<unset>"]
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
    updated_files_and_os:
      header: "Updated Files and OS:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
        - key: "type"
          eq: "AppliedFilesAndOS"
        - key: "reason"
          ne: "NotYetOccured"
        default: ["<unset>"]
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
    update_postaction_complete:
      header: "Update Postaction Complete:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
        - key: "type"
          eq: "UpdatePostActionComplete"
        - key: "reason"
          ne: "NotYetOccured"
        default: ["<unset>"]
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
    update_prepared:
      header: "Update Prepared:"
      paths:
      - path: "status#conditions"
        pathtype: "items"
        subpath: "status"
        when:
        - key: "type"
          eq: "UpdatePrepared"
        - key: "reason"
          ne: "NotYetOccured"
        default: ["<unset>"]
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            "True":
              field_colors:
              - context: "main"
                type: "status_ok"
            "False":
              field_colors:
              - context: "main"
                type: "status_not_ok"
infoview:
  name: "Machine Config Node Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["node_name", "machine_config_pool", "updated", "update_prepared", "update_executed", "update_postaction_complete", "update_complete", "resumed", "update_compatible", "updated_files_and_os", "cordoned", "drained", "rebooted", "reloaded_crio", "configuration_header", "configuration_current", "configuration_desired"]
    rows:
      configuration_current:
        header: [["  Current:", ["main", "infoheader"]]]
        path: "status#configVersion#desired"
        type: "str"
        formatting:
          field_colors:
          - type: "version"
      configuration_desired:
        header: [["  Desired:", ["main", "infoheader"]]]
        path: "status#configVersion#desired"
        type: "str"
        formatting:
          field_colors:
          - type: "version"
      configuration_header:
        header: [["Configuration:", ["main", "infoheader"]]]
      cordoned:
        header: [["Cordoned:", ["main", "infoheader"]]]
        paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
          - key: "type"
            eq: "Cordoned"
          - key: "reason"
            ne: "NotYetOccured"
          default: ["<unset>"]
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                - context: "main"
                  type: "status_ok"
              "False":
                field_colors:
                - context: "main"
                  type: "status_not_ok"
      drained:
        header: [["Drained:", ["main", "infoheader"]]]
        paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
          - key: "type"
            eq: "Drained"
          - key: "reason"
            ne: "NotYetOccured"
          default: ["<unset>"]
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                - context: "main"
                  type: "status_ok"
              "False":
                field_colors:
                - context: "main"
                  type: "status_not_ok"
      machine_config_pool:
        header: [["Machine Config ", ["main", "infoheader"]], ["P", ["main", "infoheader_shortcut"]], ["ool:", ["main", "infoheader"]]]
        path: "spec#pool#name"
        type: "str"
      node_name:
        header: [["No", ["main", "infoheader"]], ["d", ["main", "infoheader_shortcut"]], ["e Name:", ["main", "infoheader"]]]
        paths:
        - path: "metadata#ownerReferences"
          pathtype: "items"
          subpaths:
          - "name"
          when:
          - key: "kind"
            eq: "Node"
        formatter: "list"
        formatting:
          field_colors:
          - type: "host"
      rebooted:
        header: [["Rebooted:", ["main", "infoheader"]]]
        paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
          - key: "type"
            eq: "RebootedNode"
          - key: "reason"
            ne: "NotYetOccured"
          default: ["<unset>"]
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                - context: "main"
                  type: "status_ok"
              "False":
                field_colors:
                - context: "main"
                  type: "status_not_ok"
      reloaded_crio:
        header: [["Reloaded CRI-O:", ["main", "infoheader"]]]
        paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
          - key: "type"
            eq: "ReloadedCRIO"
          - key: "reason"
            ne: "NotYetOccured"
          default: ["<unset>"]
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                - context: "main"
                  type: "status_ok"
              "False":
                field_colors:
                - context: "main"
                  type: "status_not_ok"
      resumed:
        header: [["Resumed:", ["main", "infoheader"]]]
        paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
          - key: "type"
            eq: "Resumed"
          - key: "reason"
            ne: "NotYetOccured"
          default: ["<unset>"]
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                - context: "main"
                  type: "status_ok"
              "False":
                field_colors:
                - context: "main"
                  type: "status_pending"
      update_compatible:
        header: [["Update Compatible:", ["main", "infoheader"]]]
        paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
          - key: "type"
            eq: "UpdateCompatible"
          - key: "reason"
            ne: "NotYetOccured"
          default: ["<unset>"]
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                - context: "main"
                  type: "status_ok"
              "False":
                field_colors:
                - context: "main"
                  type: "status_not_ok"
      update_complete:
        header: [["Update Complete:", ["main", "infoheader"]]]
        paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
          - key: "type"
            eq: "UpdateComplete"
          - key: "reason"
            ne: "NotYetOccured"
          default: ["<unset>"]
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                - context: "main"
                  type: "status_ok"
              "False":
                field_colors:
                - context: "main"
                  type: "status_not_ok"
      update_executed:
        header: [["Update Executed:", ["main", "infoheader"]]]
        paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
          - key: "type"
            eq: "UpdateExecuted"
          - key: "reason"
            ne: "NotYetOccured"
          default: ["<unset>"]
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                - context: "main"
                  type: "status_ok"
              "False":
                field_colors:
                - context: "main"
                  type: "status_not_ok"
      updated:
        header: [["Updated:", ["main", "infoheader"]]]
        paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
          - key: "type"
            eq: "Updated"
          - key: "reason"
            ne: "NotYetOccured"
          default: ["<unset>"]
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                - context: "main"
                  type: "status_ok"
              "False":
                field_colors:
                - context: "main"
                  type: "status_not_ok"
      updated_files_and_os:
        header: [["Updated Files and OS:", ["main", "infoheader"]]]
        paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
          - key: "type"
            eq: "AppliedFilesAndOS"
          - key: "reason"
            ne: "NotYetOccured"
          default: ["<unset>"]
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                - context: "main"
                  type: "status_ok"
              "False":
                field_colors:
                - context: "main"
                  type: "status_not_ok"
      update_postaction_complete:
        header: [["Update Postaction Complete:", ["main", "infoheader"]]]
        paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
          - key: "type"
            eq: "UpdatePostActionComplete"
          - key: "reason"
            ne: "NotYetOccured"
          default: ["<unset>"]
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                - context: "main"
                  type: "status_ok"
              "False":
                field_colors:
                - context: "main"
                  type: "status_not_ok"
      update_prepared:
        header: [["Update Prepared:", ["main", "infoheader"]]]
        paths:
        - path: "status#conditions"
          pathtype: "items"
          subpath: "status"
          when:
          - key: "type"
            eq: "UpdatePrepared"
          - key: "reason"
            ne: "NotYetOccured"
          default: ["<unset>"]
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              "True":
                field_colors:
                - context: "main"
                  type: "status_ok"
              "False":
                field_colors:
                - context: "main"
                  type: "status_not_ok"
  shortcuts:
    "Open Machine Config Pool":
      key: "p"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Machine Config Pool"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        name_path: "spec#pool#name"
        kind: "MachineConfigPool"
        api_family: "machineconfiguration.openshift.io"
    "Open Node":
      key: "d"
      read_only: true
      helptext: "Open info page for Node"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        kind: "Node"
        owner_reference_path: "metadata#ownerReferences"
