kind: "MiddlewareTCP"
api_family: "traefik.io"
default_command: "middlewaretcps"
listview:
  name: "Middleware TCPs"
  group: "Network"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
