---
kind: "Middleware"
api_family: "traefik.io"
default_command: "middlewares"
listview:
  name: "Middlewares"
  group: "Network"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
