---
kind: "Middleware"
api_family: "traefik.containo.us"
default_command: "middlewares"
listview:
  name: "Middlewares (Old API)"
  group: "Network"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
