kind: MutatingWebhookConfiguration
api_family: admissionregistration.k8s.io
default_command: mutatingwebhookconfigurations
command:
- mwhcs
- mwhc
listview:
  name: Mutating Webhook Configurations
  group: API & Extendability
  field_indexes:
    Normal: [name, data, age]
  fields:
    data:
      header: "# of Webhooks:"
      paths:
      - path: "webhooks"
        type: len
      align: right
