kind: "MutatingWebhookConfiguration"
api_family: "admissionregistration.k8s.io"
default_command: "mutatingwebhookconfigurations"
command:
- "mwhcs"
- "mwhc"
listview:
  name: "Mutating Webhook Configurations"
  group: "API & Extendability"
  field_indexes:
    Normal:
      fields: ["name", "webhook_count", "age"]
  fields:
    webhook_count:
      header: "Webhooks:"
      path: "webhooks"
      type: "len"
      formatting:
        field_colors:
        - type: "numerical"
      align: "right"
  actions:
    actionlist:
      "Delete resource":
        description: "Delete resource"
        category: "Resource Level"
        confirm: true
        actionfunc: "delete_resource"
      "Force delete resource":
        description: "Delete resource (No grace period)"
        category: "Resource Level"
        confirm: true
        actionfunc: "force_delete_resource"
infoview:
  name: "Mutating Webhook Configuration Info"
  infopad:
  listpad:
    listgetter: "listgetter_path"
    listgetter_args:
      path: "webhooks"
    infogetter: "generic_infogetter"
    field_indexes:
      Normal:
        fields: ["name"]
    fields:
      name:
        header: "Name:"
        path: "name"
        type: "str"
