kind: MutatingWebhookConfiguration
api_family: admissionregistration.k8s.io
default_command: mutatingwebhookconfigurations
command:
- mwhcs
- mwhc
listview:
  name: Mutating Webhook Configurations
  group: API & Extendability
  field_indexes:
    Normal: [name, data, age]
  fields:
    data:
      header: "# of Webhooks:"
      path: webhooks
      type: len
      formatting:
        field_colors:
        - type: numerical
      align: right
