kind: MutatingWebhookConfiguration
api_family: admissionregistration.k8s.io
default_command: mutatingwebhookconfigurations
command:
- mwhcs
- mwhc
listview:
  name: Mutating Webhook Configurations
  group: API & Extendability
  fields:
  - name
  - name: data
    header: "# of Webhooks:"
    paths:
    - path: "webhooks"
      type: len
    align: right
  - age
