kind: "Network"
api_family: "config.openshift.io"
default_command: "networks.config.openshift.io"
command:
- "networks.config"
- "network.config"
listview:
  name: "Networks (Config)"
  group: "OpenShift"
  field_indexes:
    Normal: ["name", "age"]
