kind: "OAuth"
api_family: "config.openshift.io"
default_command: "oauths.config.openshift.io"
command:
- "oauths.config"
- "oauth.config"
listview:
  name: "Oauths (Config)"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
