kind: OLMConfig
api_family: operators.coreos.com
default_command: olmconfigs
command:
- olmconfs
- olmconf
listview:
  name: OLM Configs
  group: API & Extendability
  field_indexes:
    Normal: [name, age]
