kind: "OperatorHub"
api_family: "config.openshift.io"
default_command: "operatorhubs.config.openshift.io"
command:
- "operatorhubs.config"
- "operatorhub.config"
listview:
  name: "Operator Hubs (Config)"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "Operator Hub Info (Config)"
  infopad:
    row_indexes:
      Normal:
        fields: ["cluster_version"]
    rows:
      cluster_version:
        header: [["Cluster ", ["main", "infoheader"]], ["V", ["main", "infoheader_shortcut"]], ["ersion:", ["main", "infoheader"]]]
        paths:
        - path: "metadata#ownerReferences"
          pathtype: "items"
          subpaths:
          - "name"
          when:
          - key: "kind"
            eq: "ClusterVersion"
        default: "<none>"
  shortcuts:
    "Cluster Version":
      key: "v"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Cluster Version"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        owner_reference_path: "metadata#ownerReferences"
        kind: "ClusterVersion"
        api_family: "config.openshift.io"
    "Show sources":
      key: "s"
      modifier: "shift"
      read_only: true
      helptext: "Show sources"
      widget: "windowwidget"
      title: "Sources:"
      itemgetter: "get_list_fields"
      itemgetter_args:
        path: "status#sources"
        fields:
        - "name"
        - "status"
        - "disabled"
      headers: ["Name:", "Status:", "Disabled:"]
      # Not supported for now
      sortcolumn: "status"
