kind: "OperatorHub"
api_family: "config.openshift.io"
default_command: "operatorhubs.config.openshift.io"
command:
- "operatorhubs.config"
- "operatorhub.config"
listview:
  name: "Operator Hubs (Config)"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
