kind: "PriorityLevelConfiguration"
api_family: "flowcontrol.apiserver.k8s.io"
default_command: "prioritylevelconfigurations"
command:
- "priolevelconfs"
- "priolevelconf"
listview:
  name: "Priority Level Configurations"
  group: "Scheduling & Scaling"
  field_indexes:
    Normal:
      fields: ["name", "priority_type", "nominal_concurrency_shares", "queues", "hand_size", "queue_length_limit", "age"]
  fields:
    hand_size:
      header: "Hand Size:"
      path: "spec#limited#limitResponse#queuing#handSize"
      type: "raw"
      align: "right"
      formatting:
        field_colors:
        - type: "numerical"
    nominal_concurrency_shares:
      header: "Nominal Concurrency Shares:"
      paths:
      - path: ["spec#limited#nominalConcurrencyShares", "spec#limited#assuredConcurrencyShares"]
        pathtype: "value"
      align: "right"
      formatting:
        field_colors:
        - type: "numerical"
    priority_type:
      header: "Priority Type:"
      path: "spec#type"
      type: "str"
    queue_length_limit:
      header: "Queue Length List:"
      path: "spec#limited#limitResponse#queuing#queueLengthLimit"
      type: "raw"
      align: "right"
      formatting:
        field_colors:
        - type: "numerical"
    queues:
      header: "Queues:"
      path: "spec#limited#limitResponse#queuing#queues"
      type: "raw"
      align: "right"
      formatting:
        field_colors:
        - type: "numerical"
infoview:
  name: "Priority Level Configuration Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["cluster_version", "priority_type", "nominal_concurrency_shares", "queues", "hand_size", "queue_length_limit", "queues"]
    rows:
      cluster_version:
        header: [["Cluster ", ["main", "infoheader"]], ["V", ["main", "infoheader_shortcut"]], ["ersion:", ["main", "infoheader"]]]
        paths:
        - path: "metadata#ownerReferences"
          pathtype: "items"
          subpaths:
          - "name"
          when:
          - key: "kind"
            eq: "ClusterVersion"
        default: "<none>"
      hand_size:
        header: [["Hand Size:", ["main", "infoheader"]]]
        path: "spec#limited#limitResponse#queuing#handSize"
        type: "raw"
        formatting:
          field_colors:
          - type: "numerical"
      nominal_concurrency_shares:
        header: [["Nominal Concurrency Shares:", ["main", "infoheader"]]]
        paths:
        - path: "spec#limited#assuredConcurrencyShares"
          pathtype: "value"
        formatting:
          field_colors:
          - type: "numerical"
      priority_type:
        header: [["Priority Type:", ["main", "infoheader"]]]
        path: "spec#type"
        type: "str"
      queue_length_limit:
        header: [["Queue Length List:", ["main", "infoheader"]]]
        path: "spec#limited#limitResponse#queuing#queueLengthLimit"
        type: "raw"
        formatting:
          field_colors:
          - type: "numerical"
      queues:
        header: [["Queues:", ["main", "infoheader"]]]
        path: "spec#limited#limitResponse#queuing#queues"
        type: "raw"
        formatting:
          field_colors:
          - type: "numerical"
  shortcuts:
    "Cluster Version":
      key: "v"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Cluster Version"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        owner_reference_path: "metadata#ownerReferences"
        kind: "ClusterVersion"
        api_family: "config.openshift.io"
