kind: PriorityLevelConfiguration
api_family: flowcontrol.apiserver.k8s.io
default_command: prioritylevelconfigurations
command:
- priolevelconfs
- priolevelconf
listview:
  name: Priority Level Configurations
  group: Scheduling
  fields: [name, priority_type, assured_concurrency_shares, queues, hand_size, queue_length_limit, age]
