kind: PriorityLevelConfiguration
api_family: flowcontrol.apiserver.k8s.io
default_command: prioritylevelconfigurations
command:
- priolevelconfs
- priolevelconf
listview:
  name: Priority Level Configurations
  group: Scheduling & Scaling
  field_indexes:
    Normal: [name, priority_type, assured_concurrency_shares, queues, hand_size, queue_length_limit, age]
  fields:
    assured_concurrency_shares:
      header: "Assured Concurrency Shares:"
      path: "spec#limited#assuredConcurrencyShares"
      type: raw
      align: right
    hand_size:
      header: "Hand Size:"
      path: "spec#limited#limitResponse#queuing#handSize"
      type: raw
      align: right
    priority_type:
      header: "Priority Type:"
      path: "spec#type"
      type: str
    queue_length_limit:
      header: "Queue Length List:"
      path: "spec#limited#limitResponse#queuing#queueLengthLimit"
      type: raw
      align: right
    queues:
      header: "Queues:"
      path: "spec#limited#limitResponse#queuing#queues"
      type: raw
      align: right
