kind: "Project"
api_family: "config.openshift.io"
default_command: "projects.config.openshift.io"
command:
- "projects.config"
- "project.config"
- "projectconfs"
- "projectconf"
listview:
  name: "Projects (Config)"
  group: "OpenShift"
  field_indexes:
    Normal: ["name", "age"]
infoview:
  name: "Project Info (Config)"
  infopad:
