---
kind: "PrometheusRule"
api_family: "monitoring.coreos.com"
default_command: "prometheusrules"
command:
  - "promrules"
  - "promrule"
listview:
  name: "Prometheus Rules"
  group: "Monitoring"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
infoview:
  name: "Prometheus Rule Info"
  # PrometheusRule annotations contains the entire rule set;
  # this is way too much to handle for the annotations widget
  annotations: "null"
  infopad:
    row_indexes:
      Normal:
        fields: ["cluster_version"]
    rows:
      cluster_version:
        header: [["Cluster ", ["main", "infoheader"]],
                 ["V", ["main", "infoheader_shortcut"]],
                 ["ersion:", ["main", "infoheader"]]]
        paths:
          - path: "metadata#ownerReferences"
            pathtype: "items"
            subpaths:
              - "name"
            when:
              - key: "kind"
                eq: "ClusterVersion"
        default: "<none>"
  listpad:
    listgetter: "listgetter_path"
    listgetter_args:
      path: ""
    infogetter: "get_promrules_info"
    on_activation:
      call: "resourceinfodispatch"
      kind: "__PrometheusRuleData"
      api_family: "monitoring.coreos.com"
    field_indexes:
      Normal:
        fields: ["group", "rtype", "alertrecord", "duration"]
        sortcolumn: "rtype"
    fields:
      alertrecord:
        header: "Name:"
        path: "alertheader"
        type: "str"
      duration:
        header: "Duration:"
        path: "duration"
        type: "raw"
        formatter: "age"
        formatting:
          field_colors:
            - type: "numerical"
        align: "right"
      group:
        header: "Group:"
        path: "group"
        type: "str"
      rtype:
        header: "Type:"
        path: "rtype"
        type: "str"
  shortcuts:
    "Cluster Version":
      key: "v"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Cluster Version"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        owner_reference_path: "metadata#ownerReferences"
        kind: "ClusterVersion"
        api_family: "config.openshift.io"
