kind: PrometheusRule
api_family: monitoring.coreos.com
default_command: prometheusrules
command:
- promrules
- promrule
listview:
  name: Prometheus Rules
  group: Monitoring
  field_indexes:
    Normal: [namespace, name, age]
