---
kind: "ProvisioningRequestConfig"
api_family: "kueue.x-k8s.io"
default_command: "provisioningrequestconfigs"
command:
  - "provreqconfigs"
  - "provreqconfig"
  - "provreqconfs"
  - "provreqconf"
listview:
  name: "Provisioning Request Configs"
  group: "Batch Scheduling"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "Provisioning Request Config Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["provisioning_class_name", "managed_resources",
                 "retry_strategy_header",
                 "retry_strategy_backoff_limit_header",
                 "retry_strategy_backoff_limit_count",
                 "retry_strategy_backoff_base_seconds",
                 "retry_strategy_backoff_max_seconds"]
    rows:
      managed_resources:
        header: [["Managed ", ["main", "infoheader"]],
                 ["R", ["main", "infoheader_shortcut"]],
                 ["esources:", ["main", "infoheader"]]]
        path: "spec#managedResources"
        default: ["<none>"]
        type: "raw"
        formatter: "list"
      provisioning_class_name:
        header: [["Provisioning Class Name:", ["main", "infoheader"]]]
        path: "spec#provisioningClassName"
        default: "<unset>"
        type: "str"
      retry_strategy_backoff_limit_count:
        header: [["    Count:", ["main", "infoheader"]]]
        path: "spec#retryStrategy#backoffLimitCount"
        default: 3
        type: "int"
        formatter: "numerical"
      retry_strategy_backoff_limit_header:
        header: [["  Backoff Limit:", ["main", "infoheader"]]]
      retry_strategy_backoff_base_seconds:
        header: [["    Base Seconds:", ["main", "infoheader"]]]
        paths:
          - path: [["spec#retryStrategy#backoffBaseSeconds"], "s"]
            pathtype: "tuple"
            default: ["1800", ""]
        type: "list"
        formatter: "list"
        formatting:
          field_colors:
            - type: "numerical"
            - type: "unit"
          field_separators:
            - type: "no_pad"
      retry_strategy_backoff_max_seconds:
        header: [["    Max:", ["main", "infoheader"]]]
        paths:
          - path: [["spec#retryStrategy#backoffMaxSeconds"], "s"]
            pathtype: "tuple"
            default: ["1800", ""]
        type: "list"
        formatter: "list"
        formatting:
          field_colors:
            - type: "numerical"
            - type: "unit"
          field_separators:
            - type: "no_pad"
      retry_strategy_header:
        header: [["Retry Strategy:", ["main", "infoheader"]]]
  shortcuts:
    "Managed Resources":
      key: "r"
      modifier: "shift"
      read_only: true
      helptext: "List managed resources"
      widget: "windowwidget"
      title: "Managed resources:"
      itemgetter: "get_list_as_list"
      itemgetter_args:
        path: "spec#managedResources"
      # This isn't supported for now
      sortcolumn: "resource"
