kind: "ProxyConfig"
api_family: "networking.istio.io"
default_command: "wasmplugins"
listview:
  name: "Proxy Configs"
  group: "Istio"
  field_indexes:
    Normal: ["namespace", "name", "age"]
  sortcolumn: "namespace"
