kind: "Proxy"
api_family: "config.openshift.io"
default_command: "proxies.config.openshift.io"
command:
- "proxies.config"
- "proxy.config"
listview:
  name: "Proxies (Config)"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "Proxy Info (Config)"
  infopad:
    row_indexes:
      Normal:
        fields: ["trusted_ca"]
    rows:
      trusted_ca:
        header: [["Trusted CA:", ["main", "infoheader"]]]
        paths:
        - path: "spec#trustedCA#name"
          pathtype: "value"
          type: "str"
          fallback_on_empty: true
          default: "<empty>"
