kind: "ProxyConfig"
api_family: "networking.istio.io"
default_command: "proxyconfigs"
listview:
  name: "Proxy Configs"
  group: "Istio"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
