kind: "Proxy"
api_family: "config.openshift.io"
default_command: "proxies.config.openshift.io"
command:
- "proxies.config"
- "proxy.config"
listview:
  name: "Proxies (Config)"
  group: "OpenShift"
  field_indexes:
    Normal: ["name", "age"]
