---
kind: "ScheduledSparkApplication"
api_family: "sparkoperator.k8s.io"
default_command: "scheduledsparkapplications"
command:
  - "schedsparkapps"
  - "schedsparkapp"
listview:
  name: "Scheduled Spark Applications"
  group: "Workloads"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "schedule", "concurrency_policy",
               "last_scheduled", "next_scheduled", "state", "age"]
      sortcolumn: "status"
  fields:
    concurrency_policy:
      header: "Concurrency:"
      path: "spec#concurrencyPolicy"
      type: "str"
    last_scheduled:
      header: "Last Scheduled:"
      path: "status#lastRun"
      default: -1
      type: "timestamp"
      formatter: "timestamp"
    next_scheduled:
      header: "Next Scheduled:"
      path: "status#nextRun"
      default: -1
      type: "timestamp"
      formatter: "timestamp"
    schedule:
      header: "Schedule:"
      path: "spec#schedule"
      type: "str"
    state:
      header: "State:"
      path: "status#scheduleState"
      type: "str"
      formatter: "value_mapper"
      formatting:
        mapping:
          mappings:
            Scheduled:
              field_colors:
                - context: "main"
                  type: "status_pending"
  actions:
    actionlist:
      "Delete resource":
        description: "Delete resource"
        category: "Resource Level"
        confirm: true
        actionfunc: "delete_resource"
infoview:
  name: "Scheduled Spark Application Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["successful_run_history_limit", "failed_run_history_limit",
                 "concurrency_policy", "schedule", "last_scheduled",
                 "next_scheduled"]
    rows:
      concurrency_policy:
        header: [["Concurrency Policy:", ["main", "infoheader"]]]
        path: "spec#concurrencyPolicy"
        type: "raw"
      failed_run_history_limit:
        header: [["Failed Run History Limit:", ["main", "infoheader"]]]
        path: "spec#failedRunHistoryLimit"
        type: "int"
        formatter: "numerical"
      last_scheduled:
        header: [["Last Scheduled:", ["main", "infoheader"]]]
        path: "status#lastRun"
        default: -1
        type: "timestamp"
        formatter: "timestamp"
      next_scheduled:
        header: [["Next Scheduled:", ["main", "infoheader"]]]
        path: "status#nextRun"
        default: -1
        type: "timestamp"
        formatter: "timestamp"
      schedule:
        header: [["Schedule:", ["main", "infoheader"]]]
        path: "spec#schedule"
        type: "str"
      state:
        header: [["State:", ["main", "infoheader"]]]
        path: "status#scheduleState"
        type: "str"
        formatter: "value_mapper"
        formatting:
          mapping:
            mappings:
              Scheduled:
                field_colors:
                  - context: "main"
                    type: "status_pending"
      successful_run_history_limit:
        header: [["Successful Run History Limit:", ["main", "infoheader"]]]
        path: "spec#successfulRunHistoryLimit"
        type: "int"
        formatter: "numerical"
  listpad:
    listgetter: "generic_listgetter"
    listgetter_args:
      _kind: "Pod"
      _label_selector_key_values:
        - ["sparkoperator.k8s.io/scheduled-app-name", ["metadata#name"]]
    infogetter: "generic_infogetter"
    on_activation:
      call: "resourceinfodispatch"
      kind: "Pod"
    field_indexes:
      Wide:
        fields: ["namespace", "name", "pod_status", "node_name",
                 "pod_ip", "age", "restarts", "last_restart", "containers"]
        sortcolumn: "pod_status"
      Normal:
        fields: ["namespace", "name", "pod_status", "node_name",
                 "age", "restarts", "last_restart"]
        sortcolumn: "pod_status"
      Compact:
        fields: ["namespace", "name", "pod_status", "age",
                 "restarts", "last_restart"]
        sortcolumn: "pod_status"
    fields:
      containers:
        header: "Containers:"
        paths:
          - paths:
              - "spec#initContainers"
              - "spec#containers"
            pathtype: "items"
            subpaths:
              - "name"
              - subpath: "image"
                regex: ["^.+/[^:^/]+:(.+?)@.*", "^.+/[^:^/]+:(.+)"]
            type: "raw"
        formatter: "list"
        formatting:
          field_colors:
            - type: "generic"
            - type: "version"
          field_separators:
            - type: "version"
      last_restart:
        header: "Latest Restart:"
        paths:
          - path: "status#containerStatuses"
            pathtype: "items"
            subpath: ["state#running#startedAt",
                      "lastState#terminated#finishedAt"]
            when:
              - key: "restartCount"
                gt: 0
            action: "latest"
            type: "timestamp"
        default: -1
        formatter: "age"
        align: "right"
      node_name:
        header: "Node:"
        path: "spec#nodeName"
        type: "host"
        default: "<none>"
        formatting:
          field_colors:
            - type: "host"
      pod_ip:
        header: "Pod IP:"
        path: "status#podIP"
        default: "<unset>"
        type: "address"
        formatter: "address"
      restarts:
        header: "Restarts:"
        paths:
          - path: "status#containerStatuses"
            pathtype: "items"
            subpath: "restartCount"
            action: "sum"
            type: "int"
        default: 0
        formatter: "numerical"
        align: "right"
  shortcuts:
    "Spark Application template":
      key: "t"
      modifier: "shift"
      read_only: true
      helptext: "Show Spark Application template"
      action: "call"
      action_call: "view_yaml"
      action_args:
        title: "Spark Application template"
        _pass_obj: true
        path: "spec#template"
