kind: "Scheduler"
api_family: "config.openshift.io"
default_command: "schedulers.config.openshift.io"
command:
- "schedulers.config"
- "scheduler.config"
listview:
  name: "Schedulers (Config)"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
