---
kind: "ServersTransport"
api_family: "traefik.io"
default_command: "serverstransports"
command:
  - "srvtransports"
  - "srvtransport"
listview:
  name: "Servers Transports"
  group: "Network"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
