kind: Service
default_command: services
command:
- svcs
- svc
listview:
  name: Services
  group: Core
  field_indexes:
    Normal: [namespace, name, svc_type, cluster_ip, external_ips, ports_svc, age]
  sortcolumn: namespace
  fields:
    cluster_ip:
      header: "Cluster-IP:"
      path: "spec#clusterIP"
      type: str
    external_ips:
      header: "External-IPs:"
      paths:
      - path: "spec#externalIPs"
        pathtype: list
      formatter: list
    svc_type:
      header: "Type:"
      path: "spec#type"
      type: str
    # Add alternative ports_svc, that doesn't include service name
