kind: Service
default_command: services
command:
- svcs
- svc
listview:
  name: Services
  group: Core
  field_indexes:
    Wide: [namespace, name, svc_type, cluster_ips, external_ips, ports_svc, age]
    Normal: [namespace, name, svc_type, cluster_ips, external_ips, ports_svc_compact, age]
  sortcolumn: namespace
  fields:
    # => clusterIPs
    cluster_ips:
      header: "Cluster-IPs:"
      paths:
      - path: ["spec#clusterIPs", "spec#clusterIP"]
        pathtype: list
        default: "<none>"
        none_str_as_none: true
      formatter: address
    external_ips:
      header: "External-IPs:"
      paths:
      - path: "spec#externalIPs"
        pathtype: list
      formatter: address
    svc_type:
      header: "Type:"
      path: "spec#type"
      type: str
    ports_svc:
      header: "Ports:"
      paths:
      - path: "spec#ports"
        pathtype: items
        subpaths:
        - name
        - port
        - protocol
        type: raw
      formatter: list
      formatting:
        field_colors:
        - type: service
        - type: port
        - type: protocol
        field_separators:
        - type: port
        - type: service
    ports_svc_compact:
      header: "Ports:"
      paths:
      - path: "spec#ports"
        pathtype: items
        subpaths:
        - port
        - protocol
        type: raw
      formatter: list
      formatting:
        field_colors:
        - type: port
        - type: protocol
        field_separators:
        - type: service
        ellipsise: 3
