kind: Service
default_command: services
command:
- svcs
- svc
listview:
  name: Services
  group: Core
  fields: [namespace, name, svc_type, cluster_ip, external_ip, ports_svc, age]
  sortcolumn: namespace
