---
kind: "ServiceCertSignerOperatorConfig"
api_family: "servicecertsigner.config.openshift.io"
default_command: "servicecertsigneroperatorconfigs"
command:
- "svccertsigneropconfs"
- "svccertsigneropconf"
listview:
  name: "Service Cert Signer Operator Configs"
  group: "Authorization & Access Control"
  field_indexes:
    Normal:
      fields: ["name", "age"]
