kind: "TLSOption"
api_family: "traefik.containo.us"
default_command: "tlsoptions"
listview:
  name: "TLS Options"
  group: "Network"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
