kind: "TLSStore"
api_family: "traefik.containo.us"
default_command: "tlsstores"
listview:
  name: "TLS Stores (Old API)"
  group: "Network"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
