---
kind: "TLSStore"
api_family: "traefik.io"
default_command: "tlsstores"
listview:
  name: "TLS Stores"
  group: "Network"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
