kind: "TraefikService"
api_family: "traefik.io"
default_command: "traefikservices"
command:
- "traefiksvcs"
- "traefiksvc"
listview:
  name: "Traefik Services"
  group: "Network"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
