kind: "TraefikService"
api_family: "traefik.containo.us"
default_command: "traefikservices"
command:
- "traefiksvcs"
- "traefiksvc"
listview:
  name: "Traefik Services"
  group: "Network"
  field_indexes:
    Normal: ["namespace", "name", "age"]
  sortcolumn: "namespace"
