kind: "TrainedModel"
api_family: "serving.kserve.io"
default_command: "trainedmodels"
listview:
  name: "Trained Models"
  group: "Machine Learning"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
infoview:
  name: "Trained Model Info"
  infopad:
