---
kind: "UnitedDeployment"
api_family: "apps.kruise.io"
default_command: "uniteddeployments"
command:
  - "kruiseunideps"
  - "kruiseunidep"
listview:
  name: "United Deployments"
  group: "Kruise"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "desired_replicas", "current_replicas",
               "ready_replicas", "uptodate_replicas", "age"]
      sortcolumn: "namespace"
  fields:
    current_replicas:
      header: "Current:"
      paths:
        - path: ["status#replicas", "spec#replicas"]
          pathtype: "comparison"
          default: [0, 0]
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
            - min: 0
              max: 1
              field_colors:
                - context: "main"
                  type: "status_ok"
            - default: true
              field_colors:
                - context: "main"
                  type: "status_not_ok"
      align: "right"
    desired_replicas:
      header: "Desired:"
      path: "spec#replicas"
      default: 0
      type: "int"
      formatter: "numerical"
      align: "right"
    ready_replicas:
      header: "Ready:"
      paths:
        - path: ["status#readyReplicas", "spec#replicas"]
          pathtype: "comparison"
          default: [0, 0]
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
            - min: 0
              max: 1
              field_colors:
                - context: "main"
                  type: "status_ok"
            - min: -1
              max: 0
              field_colors:
                - context: "main"
                  type: "status_pending"
            - default: true
              field_colors:
                - context: "main"
                  type: "status_not_ok"
      align: "right"
    uptodate_replicas:
      header: "Up to Date:"
      paths:
        - path: ["status#updatedReplicas", "spec#replicas"]
          pathtype: "comparison"
          default: [0, 0]
      formatter: "value_mapper"
      formatting:
        mapping:
          ranges:
            - min: 0
              max: 1
              field_colors:
                - context: "main"
                  type: "status_ok"
            - min: -1
              max: 0
              field_colors:
                - context: "main"
                  type: "status_pending"
            - default: true
              field_colors:
                - context: "main"
                  type: "status_pending"
      align: "right"
  actions:
    actionlist:
      "Delete resource":
        description: "Delete resource"
        category: "Resource Level"
        confirm: true
        actionfunc: "delete_resource"
infoview:
  name: "United Deployment Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["label_selector", "replicas", "update_strategy",
                 "update_strategy_manual_update_partition"]
    rows:
      label_selector:
        header: [["Label Selector:", ["main", "infoheader"]]]
        paths:
          - path: ["spec#selector#matchLabels"]
            pathtype: "key_value"
            default: ["<none>"]
        formatter: "list"
        formatting:
          field_colors:
            - type: "key"
            - type: "value"
          field_separators:
            - type: "selector"
      replicas:
        header: [["Replicas:", ["main", "infoheader"]]]
        paths:
          - path: [["spec#replicas"], " Desired",
                   ["status#replicas"], " Current",
                   ["status#readyReplicas"], " Ready",
                   ["status#updatedReplicas"], " Up to Date"]
            pathtype: "tuple"
            default: [0, "", 0, "", 0, "", 0, ""]
        formatter: "list"
        formatting:
          field_colors:
            - type: "numerical"
            - type: "generic"
            - type: "numerical"
            - type: "generic"
            - type: "numerical"
            - type: "generic"
            - type: "numerical"
            - type: "generic"
          field_separators:
            - type: "no_pad"
            - type: "fraction_spaced"
            - type: "no_pad"
            - type: "fraction_spaced"
            - type: "no_pad"
            - type: "fraction_spaced"
            - type: "no_pad"
      update_strategy:
        header: [["Update Strategy:", ["main", "infoheader"]]]
        path: "spec#updateStrategy#type"
        type: "str"
      update_strategy_manual_update_partition:
        header: [["  Manual Update Partitions:", ["main", "infoheader"]]]
        type: "raw"
        paths:
          - path: "spec#updateStrategy#manualUpdate#partitions"
            pathtype: "key_value"
            default: ["<none>"]
        formatter: "list"
        formatting:
          field_colors:
            - type: "key"
            - type: "value"
          field_separators:
            - type: "keyvalue"
  listpad:
    listgetter: "generic_listgetter"
    listgetter_args:
      _kind: "Pod"
      _label_selector_path: "spec#selector#matchLabels"
    infogetter: "generic_infogetter"
    on_activation:
      call: "resourceinfodispatch"
      kind: "Pod"
    field_indexes:
      Wide:
        fields: ["namespace", "name", "pod_status", "node_name", "pod_ip",
                 "age", "restarts", "last_restart", "containers"]
        sortcolumn: "pod_status"
      Normal:
        fields: ["namespace", "name", "pod_status", "node_name", "age",
                 "restarts", "last_restart"]
        sortcolumn: "pod_status"
      Compact:
        fields: ["namespace", "name", "pod_status", "age", "restarts",
                 "last_restart"]
        sortcolumn: "pod_status"
    fields:
      containers:
        header: "Containers:"
        paths:
          - paths:
              - "spec#initContainers"
              - "spec#containers"
            pathtype: "items"
            subpaths:
              - "name"
              - subpath: "image"
                regex: ["^.+/[^:^/]+:(.+?)@.*", "^.+/[^:^/]+:(.+)"]
            type: "raw"
        formatter: "list"
        formatting:
          field_colors:
            - type: "generic"
            - type: "version"
          field_separators:
            - type: "version"
      last_restart:
        header: "Latest Restart:"
        paths:
          - path: "status#containerStatuses"
            pathtype: "items"
            subpath: ["state#running#startedAt",
                      "lastState#terminated#finishedAt"]
            when:
              - key: "restartCount"
                gt: 0
            action: "latest"
            type: "timestamp"
        default: -1
        formatter: "age"
        align: "right"
      node_name:
        header: "Node:"
        path: "spec#nodeName"
        type: "host"
        default: "<none>"
        formatting:
          field_colors:
            - type: "host"
      pod_ip:
        header: "Pod IP:"
        path: "status#podIP"
        default: "<unset>"
        type: "address"
        formatter: "address"
      restarts:
        header: "Restarts:"
        paths:
          - path: "status#containerStatuses"
            pathtype: "items"
            subpath: "restartCount"
            action: "sum"
            type: "int"
        default: 0
        formatter: "numerical"
        align: "right"
  shortcuts:
    "Pod template":
      key: "t"
      modifier: "shift"
      read_only: true
      helptext: "Show Pod template"
      action: "call"
      action_call: "view_yaml"
      action_args:
        title: "Pod template"
        _pass_obj: true
        path: "spec#template"
    "Topology":
      key: "t"
      read_only: true
      helptext: "Show topology"
      action: "call"
      action_call: "view_yaml"
      action_args:
        title: "Topolgy"
        _pass_obj: true
        path: "spec#topology"
