---
kind: "ValidatingWebhookConfiguration"
api_family: "admissionregistration.k8s.io"
default_command: "validatingwebhookconfigurations"
command:
- "vwhcs"
- "vwhc"
listview:
  name: "Validating Webhook Configurations"
  group: "API & Extendability"
  field_indexes:
    Normal:
      fields: ["name", "webhook_count", "age"]
  fields:
    webhook_count:
      header: "Webhooks:"
      path: "webhooks"
      type: "len"
      formatting:
        field_colors:
        - type: "numerical"
      align: "right"
  actions:
    actionlist:
      "Delete resource":
        description: "Delete resource"
        category: "Resource Level"
        confirm: true
        actionfunc: "delete_resource"
      "Force delete resource":
        description: "Delete resource (No grace period)"
        category: "Resource Level"
        confirm: true
        actionfunc: "force_delete_resource"
infoview:
  name: "Validating Webhook Configuration Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["cluster_version"]
    rows:
      cluster_version:
        header: [["Cluster ", ["main", "infoheader"]], ["V", ["main", "infoheader_shortcut"]], ["ersion:", ["main", "infoheader"]]]
        paths:
        - path: "metadata#ownerReferences"
          pathtype: "items"
          subpaths:
          - "name"
          when:
          - key: "kind"
            eq: "ClusterVersion"
        default: "<none>"
  listpad:
    on_activation:
      call: "resourceinfodispatch"
      kind: "__ValidatingWebhook"
      api_family: "admissionregistration.k8s.io"
    listgetter: "listgetter_path"
    listgetter_args:
      path: "webhooks"
    infogetter: "generic_infogetter"
    field_indexes:
      Normal:
        fields: ["name"]
    fields:
      name:
        header: "Name:"
        path: "name"
        type: "str"
  shortcuts:
    "Cluster Version":
      key: "v"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for Cluster Version"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        owner_reference_path: "metadata#ownerReferences"
        kind: "ClusterVersion"
        api_family: "config.openshift.io"
