kind: ValidatingWebhookConfiguration
api_family: admissionregistration.k8s.io
default_command: validatingwebhookconfigurations
command:
- vwhcs
- vwhc
listview:
  name: Validating Webhook Configurations
  group: API & Extendability
  field_indexes:
    Normal: [name, data, age]
  fields:
    data:
      header: "# of Webhooks:"
      paths:
      - path: "webhooks"
        type: len
      align: right
