- name: "ingress-nginx"
  show_in_selector: false
  matchkeys:
  - pod_name: "ingress-nginx-controller"
  - pod_name: "rke2-ingress-nginx-controller"
  parser_rules:
  - name: "glog"
  - name: "expand_event"
  - name: "key_value_with_leading_message"
  - name: "ts_8601"
  - name: "bracketed_severity"
  - name: "http"
    options:
      reformat_timestamps: true
  - name: "override_severity"
    overrides:
    - matchtype: "startswith"
      matchkey: "NGINX Ingress controller"
      loglevel: "notice"
    - matchtype: "startswith"
      matchkey: "  Release:"
      loglevel: "notice"
    - matchtype: "startswith"
      matchkey: "Trace["
      loglevel: "debug"
