- name: "openshift-config"
  show_in_selector: false
  matchkeys:
  - pod_name: "openshift-config-operator"
    container_name: "openshift-config-operator"
  parser_rules:
  - name: "glog"
  - name: "expand_event"
  - name: "override_severity"
    overrides:
    - matchtype: "startswith"
      matchkey: "config-operator version "
      loglevel: "notice"
