- name: "prometheus"
  show_in_selector: false
  matchkeys:
  - pod_name: "prometheus"
    container_name: "prometheus-adapter"
  parser_rules:
  - name: "glog"
  - name: "override_severity"
    overrides:
    - matchtype: "startswith"
      matchkey: "Trace["
      loglevel: "debug"
  - name: "key_value_with_leading_message"
- name: "prometheus"
  show_in_selector: false
  matchkeys:
  - pod_name: "blackbox-exporter"
    container_name: "module-configmap-reloader"
  - container_name: "prometheus-server-configmap-reload"
  parser_rules:
  - name: "ts_8601"
- name: "prometheus"
  show_in_selector: false
  matchkeys:
  - pod_name: "kube-prometheus"
    container_name: "kube-state-metrics"
  parser_rules:
  - name: "glog"
  - name: "override_severity"
    overrides:
    - matchtype: "startswith"
      matchkey: "Trace["
      loglevel: "debug"
- name: "prometheus"
  show_in_selector: false
  matchkeys:
  - pod_name: "node-exporter"
    container_name: "node-exporter"
  - pod_name: "kube-prometheus"
    container_name: "node-exporter"
  - pod_name: "kube-prometheus"
    container_name: "prometheus-operator"
  parser_rules:
  - name: "key_value"
    options:
      versions:
      - "version"
  - name: "override_severity"
    overrides:
    - matchtype: "startswith"
      matchkey: "Starting node_exporter"
      loglevel: "notice"
- name: "prometheus"
  show_in_selector: false
  matchkeys:
  - pod_name: "prometheus"
    container_name: "prometheus"
  - pod_name: "prometheus"
    container_name: "config-reloader"
  - pod_name: "prometheus"
    container_name: "init-config-reloader"
    container_type: "init_container"
  - pod_name: "blackbox-exporter"
    container_name: "blackbox-exporter"
  - pod_name: "alertmanager"
  parser_rules:
  - name: "key_value"
    options:
      versions:
      - "version"
  - name: "override_severity"
    overrides:
    - matchtype: "startswith"
      matchkey: "Starting Prometheus"
      loglevel: "notice"
    - matchtype: "startswith"
      matchkey: "Starting blackbox_exporter"
      loglevel: "notice"
    - matchtype: "startswith"
      matchkey: "Starting Alertmanager"
      loglevel: "notice"
    - matchtype: "startswith"
      matchkey: "Starting prometheus-config-reloader"
      loglevel: "notice"
