- name: prometheus
  show_in_selector: false
  matchkeys:
  - pod_name: prometheus
    container_name: prometheus-adapter
  parser_rules:
  - name: glog
  - name: key_value_with_leading_message
- name: prometheus
  show_in_selector: false
  matchkeys:
  - pod_name: prometheus
    container_name: prometheus
  - pod_name: blackbox-exporter
    container_name: blackbox-exporter
  - pod_name: alertmanager
  parser_rules:
  - name: key_value
  - name: override_severity
    overrides:
    - matchtype: startswith
      matchkey: "Starting Prometheus"
      loglevel: notice
    - matchtype: startswith
      matchkey: "Starting blackbox_exporter"
      loglevel: notice
    - matchtype: startswith
      matchkey: "Starting Alertmanager"
      loglevel: notice
    - matchtype: startswith
      matchkey: "Starting prometheus-config-reloader"
      loglevel: notice
- name: prometheus
  show_in_selector: false
  matchkeys:
  - pod_name: blackbox-exporter
    container_name: module-configmap-reloader
  parser_rules:
  - name: ts_8601
