- hosts: selection:!nas
  vars:
    metadata:
      description: "Add Kubernetes repository"
      playbook_types:
      - "internal"
  gather_subset:
  - '!min'
  - '!all'
  - 'distribution'
  become: true
  become_user: "root"
  tasks:
  - name: "Creating /usr/local/keyrings"
    ansible.builtin.file:
      path: "/usr/local/keyrings"
      state: "directory"
      mode: "0755"
    when: ansible_os_family == 'Debian'
  - name: "Fetching Kubernetes repository key"
    ansible.builtin.get_url:
      url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
      dest: "/usr/local/keyrings/packages.cloud.google.com-keyring.gpg"
      mode: "0644"
      force: true
      use_proxy: "{{ use_proxy }}"
    environment:
      https_proxy: "{{ https_proxy }}"
    when: ansible_os_family == 'Debian'
  - name: "Configuring package repository for Kubernetes"
    ansible.builtin.template:
      dest: "/etc/apt/sources.list.d/kubernetes.list"
      src: "templates/etc/apt/sources.list.d/kubernetes.list.j2"
      mode: "0644"
    when: ansible_os_family == 'Debian'
  - name: "Configuring package repository proxy for Kubernetes"
    ansible.builtin.template:
      dest: "/etc/apt/apt.conf.d/01proxy-kubernetes"
      src: "templates/etc/apt/apt.conf.d/01proxy-kubernetes.j2"
      mode: "0644"
    when: (ansible_os_family == 'Debian') and (use_proxy == "yes")
  - name: "Updating package cache"
    ansible.builtin.apt: update_cache=yes force_apt_get=yes
    when: ansible_os_family == 'Debian'
  - name: "Configuring package repository for Kubernetes"
    ansible.builtin.template:
      dest: "/etc/yum.repos.d/kubernetes.repo"
      src: "templates/etc/yum.repos.d/kubernetes.repo.j2"
      mode: "0644"
    when: ansible_os_family == 'RedHat'
  - name: "Installing dnf-plugin-versionlock"
    ansible.builtin.dnf:
      update_cache: true
      name: "dnf-plugin-versionlock"
    when: ansible_os_family == 'RedHat'
