- hosts: selection
  vars:
    metadata:
      description: "Cordon node"
      playbook_types:
      - "node"
      allow_on_control_plane: "single"
      category: "Scheduling"
  gather_facts: false
  tasks:
  - name: "Cordoning node"
    ansible.builtin.shell: |
      nodes="{{ groups["selection"] | join(" ") }}"
      kubectl cordon ${nodes}
    delegate_to: localhost
