- hosts: selection
  vars:
    metadata:
      description: Execute command (as root)
      confirm: true
      query:
        string: Command to execute
        function: string
        variable: command
      category: Administration
  gather_facts: false
  become: true
  become_user: root
  tasks:
  - name: Executing command as root
    shell: "{{ command }}"
