- hosts: "selection"
  vars:
    metadata:
      description: "Execute command"
      summary:
        "Other actions":
        - "Executes a user specified action"
      confirm: true
      requires_cluster_info: true
      query:
        string: "Command to execute"
        function: "string"
        variable: "command"
      category: "Administration"
  gather_facts: false
  tasks:
  - name: "Executing command"  # noqa command-instead-of-shell fqcn-builtins
    shell: "{{ command }}"
    changed_when: false
