- hosts: selection
  vars:
    metadata:
      description: "Execute command"
      confirm: true
      query:
        string: "Command to execute"
        function: "string"
        variable: "command"
      category: "Administration"
  gather_facts: false
  tasks:
  - name: "Executing command"
    shell: "{{ command }}"
