- hosts: "selection"
  name: "Execute command (as root)"
  vars:
    metadata:
      description: "Execute command (as root)"
      summary:
        "Other actions":
        - description: "Executes a user specified action with root permissions"
      confirm: true
      query:
        string: "Command to execute"
        function: "string"
        variable: "command"
      category: "Administration"
  gather_facts: false
  become: true
  become_user: "root"
  tasks:
  - name: "Executing command as root"  # noqa command-instead-of-shell fqcn-builtins
    shell: "{{ command }}"
    changed_when: false
