---
# yamllint disable rule:line-length
- name: "Delete node from cluster"
  hosts: "localhost"
  vars:
    metadata:
      description: "Delete node from cluster"
      summary:
        "Kubernetes actions":
          - description: "Forcibly drains the specified nodes"
          - description: "Deletes the specified nodes from the clusters"
      playbook_types:
        - "internal"
      category: "Administration"
  gather_facts: false
  tasks:
    - name: "Deleting node from cluster"
      ansible.builtin.shell:
        executable: "/bin/bash"
        cmd: |
          set -o pipefail
          nodes="{{ groups["selection"] | join(" ") }}"
          minor_version="$(kubectl version | grep "Client Version" | sed -e "s/.*Minor:\"\([0-9]*\)\".*/\1/;s/^Client Version: v[0-9]*\.\([0-9]*\)\..*$/\1/")"
          kubectl drain --disable-eviction=true --delete-local-data --force --grace-period=0 --ignore-daemonsets ${nodes}
          kubectl delete node ${nodes}
      when: "inventory_hostname == ansible_play_hosts_all[0]"
      changed_when: true
