- hosts: "selection"
  vars:
    metadata:
      description: "Drain node"
      summary:
        "Kubernetes actions":
        - description: "Drains the specified nodes"
      playbook_types:
      - "node"
      allow_on_control_plane: "single"
      category: "Scheduling"
  gather_facts: false
  tasks:
  - name: "Draining node"  # noqa fqcn-builtins
    shell: |
      nodes="{{ groups["selection"] | join(" ") }}"
      kubectl drain --delete-local-data --ignore-daemonsets ${nodes}
    delegate_to: "localhost"
    changed_when: false
