- hosts: "selection"
  name: "Drain node"
  vars:
    metadata:
      description: "Drain node"
      summary:
        "Kubernetes actions":
        - description: "Drains the specified nodes"
      playbook_types:
      - "node"
      allow_on_control_plane: "single"
      category: "Scheduling"
  gather_facts: false
  tasks:
  - name: "Draining node"  # noqa fqcn-builtins
    shell: |
      nodes="{{ groups["selection"] | join(" ") }}"
      minor_version="$(kubectl version | grep "Client Version" | sed -e "s/.*Minor:\"\([0-9]*\)\".*/\1/;s/^Client Version: v[0-9]*\.\([0-9]*\)\.[0-9]*$/\1/")"
      if [ "${minor_version}" -ge 20 ]; then
        kubectl drain --delete-emptydir-data --ignore-daemonsets ${nodes}
      else
        kubectl drain --delete-local-data --ignore-daemonsets ${nodes}
      fi
    delegate_to: "localhost"
    run_once: true
    changed_when: false
