---
# yamllint disable rule:line-length
- name: "Fetch dmesg"
  hosts: "selection"
  vars:
    logpath: "/home/tao/.cmt/ansible/logs"
    metadata:
      description: "Fetch dmesg"
      summary:
        "Fetched files":
          - description: "remote:dmesg => localhost:/home/{{ ansible_user }}/.cmt/ansible/{{ timestamp }}_fetch_dmesg"
      category: "Administration"
      quiet: true
      read_only: true
  gather_facts: false
  become: true
  become_user: "root"
  tasks:
    - name: "Fetching dmesg"
      ansible.builtin.shell: |
        # journalctl -k --no-pager -ojson -n 1000
        journalctl -k
      changed_when: false
