- hosts: "selection"
  vars:
    logpath: "/home/tao/.ikt/ansible/logs"
    metadata:
      description: "Fetch dmesg"
      category: "Administration"
      quiet: true
      read_only: true
  gather_facts: false
  become: true
  become_user: "root"
  tasks:
  - name: "Fetching dmesg"  # noqa command-instead-of-shell fqcn-builtins
    shell: |
      # journalctl -k --no-pager -ojson -n 1000
      journalctl -k
    changed_when: false
