- hosts: selection
  vars:
    logpath: /home/tao/.ikt/ansible/logs
    metadata:
      description: Fetch dmesg
      category: Administration
      quiet: true
  gather_facts: false
  become: true
  become_user: root
  tasks:
  - name: Fetch dmesg
    shell: journalctl -k # --no-pager -ojson -n 1000
