- hosts: selection
  vars:
    unit: "kubelet"
    logpath: "/home/tao/.ikt/ansible/logs"
    metadata:
      description: "Fetch a journald log for the specified unit"
      query:
        string: "Unit to fetch log for"
        function: "string"
        variable: "unit"
      quiet: true
      category: "Administration"
      read_only: true
  gather_facts: false
  become: true
  become_user: root
  tasks:
  - name: "Fetching a journald log"
    ansible.builtin.shell: journalctl -u "{{ unit }}" --no-pager -n 1000
