# XXX: This won't work with multiple controlplanes; we need to fetch from the first controlplane
- hosts: "selection:&controlplane"
  vars:
    metadata:
      description: "Copy /etc/kubernetes/admin.conf from control plane to .kube on localhost"
      playbook_types:
      - "internal"
      category: "Setup"
  gather_facts: false
  tasks:
  - name: "Creating .kube if it doesn't exist"
    ansible.builtin.file:
      path: "~/.kube"
      state: "directory"
      mode: "0700"
    delegate_to: "localhost"
  - name: "Copying /etc/kubernetes/admin.conf from control plane to localhost"
    ansible.builtin.fetch:
      become: true
      become_user: "root"
      src: "/etc/kubernetes/admin.conf"
      dest: "~/.kube/config.{{ cluster_name }}"
      flat: true
      mode: "0600"
