- hosts: "selection"
  name: "Drain node (No grace period)"
  vars:
    metadata:
      description: "Drain node (No grace period)"
      summary:
        "Kubernetes actions":
        - description: "Forcibly drains the specified nodes"
      playbook_types:
      - "internal"
      - "node"
      allow_on_control_plane: "never"
      category: "Scheduling"
  gather_facts: false
  tasks:
  - name: "Draining node (No grace period)"  # noqa fqcn-builtins risky-shell-pipe
    shell: |
      nodes="{{ groups["selection"] | join(" ") }}"
      minor_version="$(kubectl version | grep "Client Version" | sed -e "s/.*Minor:\"\([0-9]*\)\".*/\1/;s/^Client Version: v[0-9]*\.\([0-9]*\)\.[0-9]*$/\1/")"
      if [ "${minor_version}" -lt 18 ]; then
        kubectl drain --delete-local-data --force --grace-period=0 --ignore-daemonsets ${nodes}
      elif [ "${minor_version}" -ge 20 ]; then
        kubectl drain --disable-eviction=true --delete-emptydir-data --force --grace-period=0 --ignore-daemonsets ${nodes}
      else
        kubectl drain --disable-eviction=true --delete-local-data --force --grace-period=0 --ignore-daemonsets ${nodes}
      fi
    delegate_to: "localhost"
    run_once: true
    changed_when: false
