- hosts: "selection"
  name: "Get host facts"
  vars:
    metadata:
      description: "Get host facts"
      summary:
        "Information gathering":
        - description: "Fetches host information"
      playbook_types:
      - "internal"
      category: "SHOULD NOT SHOW UP"
      read_only: true
  gather_facts: false
  tasks:
  - name: "Gathering host facts"
    ansible.builtin.setup:
