- hosts: selection
  vars:
    metadata:
      description: Get package versions
      playbook-types:
      - internal
      category: SHOULD NOT SHOW UP
  gather_facts: false
  tasks:
  - name: Gathering host facts
    ansible.builtin.setup:
