- hosts: selection
  vars:
    metadata:
      description: Purge kubeadm
      time_consumption: Moderately slow
      playbook_types:
      - internal
      category: Administration
  gather_subset:
  - '!min'
  - '!all'
  - distribution
  become: true
  become_user: root
  tasks:
  - name: Unmarking packages as held
    shell: apt-mark unhold "{{ item }}" || true
    loop: "{{ held_packages }}"
    when: ansible_os_family == 'Debian'
  - name: Removing Kubernetes packages
    apt:
      name: "{{ packages }}"
      force_apt_get: true
      state: absent
      purge: true
    when: ansible_os_family == 'Debian'
  - name: Removing directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - /etc/kubernetes
    - /etc/systemd/system/kubelet.service.d
    - /var/lib/etcd
    - /var/lib/kubelet
  - name: Reloading systemd configuration
    systemd:
      daemon_reload: true
