- hosts: "selection"
  vars:
    metadata:
      description: "Setup a Kubernetes control plane using kubeadm"
      time_consumption: "Slow"
      playbook_types:
      - "internal"
      category: "Setup"
  gather_subset:
  - "!min"
  - "!all"
  - "distribution"
  become: true
  become_user: "root"
  tasks:
  - name: "Checking if cluster is already running"  # noqa fqcn-builtins
    shell: |
      lsof -i -P -n | grep 6443.*LISTEN > /dev/null
    register: "port_check"
    failed_when: false
    changed_when: false
  - name: "Creating temporary file for cluster configuration"
    ansible.builtin.tempfile:
      state: file
      suffix: temp
    register: cluster_config
  - name: "Creating cluster configuration"
    ansible.builtin.template:
      dest: "{{ cluster_config.path }}"
      src: "templates/config/clusterconfig.yaml.j2"
      mode: "0640"
  - name: "Enabling kubelet"
    ansible.builtin.systemd:
      name: "kubelet"
      enabled: true
      state: "started"
    when: "ansible_os_family == 'RedHat'"
  - name: "Pulling Kubernetes images"  # noqa fqcn-builtins
    shell: |
      if [ -n "{{ https_proxy }}" ]; then
        export https_proxy={{ https_proxy }}
      else
        export https_proxy=
      fi
      kubeadm config --config {{ cluster_config.path }} images pull
    when: "port_check.rc == 1"
  - name: "Initialising Kubernetes cluster"  # noqa fqcn-builtins
    command: "kubeadm init --config {{ cluster_config.path }} --skip-token-print"
    when: "port_check.rc == 1"
  - name: "Creating permanent join token"  # noqa fqcn-builtins
    command: "kubeadm token create --kubeconfig /etc/kubernetes/admin.conf --ttl 0 --print-join-command"
    when: "port_check.rc == 1"
  - name: "Remove temporary cluster configuration file"
    ansible.builtin.file:
      path: "{{ cluster_config.path }}"
      state: absent
    when: cluster_config.path is defined
