- hosts: selection:&nodes:!controlplane:!nas
  vars:
    metadata:
      description: Remove Kubernetes node from cluster
      time_consumption: Slow
      playbook-types:
      - node
      confirm: True
      allow-on-control-plane: never
      run-before:
      - delete_node
      run-after:
      - teardown_cni
      remove-from-groups:
      - nodes
      category: Administration
  gather_facts: no
  become: True
  become_user: root
  tasks:
  - name: Tear down Kubernetes
    shell: |
      kubeadm version > /dev/null 2> /dev/null && kubeadm reset -f
  - name: Unmarking packages as held
    shell: apt-mark unhold kubeadm kubectl kubelet || true
    when: ansible_os_family == 'Debian'
  - name: Removing Kubernetes packages
    apt:
      pkg:
      - kubeadm
      - kubectl
      - kubelet
      - kubernetes-cni
      force_apt_get: yes
      state: absent
      purge: yes
    when: ansible_os_family == 'Debian'
