- hosts: "selection"
  name: "Tear down kubeadm cluster"
  vars:
    metadata:
      description: "Tear down kubeadm cluster"
      time_consumption: "Slow"
      summary:
        "Kubernetes actions":
        - description: "Resets the Kubernetes configuration"
        - description: "Kills the API-server"
      playbook_types:
      - "internal"
      category: "Administration"
  gather_facts: false
  become: true
  become_user: "root"
  tasks:
  - name: "Tearing down Kubernetes"  # noqa fqcn-builtins
    shell: |
      kubeadm version > /dev/null 2> /dev/null && kubeadm reset -f
      killall -q kube-apiserver || true
    changed_when: false
