- hosts: selection:&nodes:!controlplane:!nas
  vars:
    metadata:
      description: Remove Kubernetes node from cluster
      time_consumption: Slow
      playbook_types:
      - node
      confirm: true
      allow_on_control_plane: never
      run_before:
      - delete_node
      run_after:
      - teardown_cni
      remove_from_groups:
      - nodes
      category: Administration
  gather_subset:
  - '!min'
  - '!all'
  - distribution
  become: true
  become_user: root
  tasks:
  - name: Tear down Kubernetes
    shell: |
      if kubeadm version > /dev/null 2> /dev/null; then
        kubeadm reset -f
      fi
  - name: Unmarking packages as held
    shell: apt-mark unhold kubeadm kubectl kubelet || true
    when: ansible_os_family == 'Debian'
  - name: Removing Kubernetes packages
    apt:
      pkg:
      - kubeadm
      - kubectl
      - kubelet
      - kubernetes-cni
      force_apt_get: true
      state: absent
      purge: true
    when: ansible_os_family == 'Debian'
