# description: listgpus:List GPUs
- hosts: selection
  vars:
    metadata:
      description: "List GPUs"
      category: "Information"
      read_only: true
  gather_facts: false
  tasks:
  - name: "Listing GPUs"
    shell: lspci -nn | grep -E "VGA|Display"
    changed_when: false
