- hosts: "selection"
  name: "List GPUs"
  vars:
    metadata:
      description: "List GPUs"
      playbook_types:
      - "cmtinv"
      - "inventory"
      - "nodes"
      category: "Information"
      summary:
        "Information gathering":
        - description: "Lists GPUs (VGA|Display)"
      read_only: true
  gather_facts: false
  become: true
  become_user: "root"
  tasks:
  - name: "Listing GPUs"  # noqa fqcn-builtins risky-shell-pipe
    shell: |
      lspci -nn | grep -E "VGA|Display"
    changed_when: false
