- hosts: "selection"
  vars:
    metadata:
      description: "Ping nodes by fetching /proc/{loadavg,meminfo,stat}"
      # playbook_types:
      # - "internal"
      category: "Information"
      quiet: true
      read_only: true
  gather_facts: false
  become: true
  become_user: "root"
  tasks:
  - name: "Fetching /proc/loadavg"  # noqa fqcn-builtins
    command: "cat /proc/loadavg"
    changed_when: false
  - name: "Fetching /proc/meminfo"  # noqa fqcn-builtins
    command: "cat /proc/meminfo"
    changed_when: false
  - name: "Fetching /proc/stat"  # noqa fqcn-builtins
    command: "cat /proc/stat"
    changed_when: false
