- hosts: selection
  vars:
    metadata:
      description: "Show NVidia information"
      category: "Information"
      read_only: true
  gather_facts: false
  tasks:
  - name: "Showing NVidia information"
    ansible.builtin.shell: |
      if [ -x /usr/bin/nvidia-smi ]; then
        nvidia-smi | sed -e '/^\s*$/q'
      else
        printf -- "[SKIP] nvidia-smi not installed\n"
      fi
    changed_when: false
