---
- name: "Ping"
  hosts: "selection"
  vars:
    metadata:
      description: "Ping"
      summary:
        "Other actions":
          - description: "Pings hosts using Ansible ping"
      playbook_types:
        - "internal"
      category: "Information"
      read_only: true
  gather_facts: false
  tasks:
    - name: "Ping"
      ansible.builtin.ping:
