- hosts: "selection"
  vars:
    metadata:
      description: "Check whether host is suitable for use as a Control Plane / Node"
      playbook_types:
      - "internal"
      gather_facts: true
      category: "Setup"
  become: true
  become_user: "root"
  tasks:
  - name: "Checking whether the host runs an Operating System supported for control planes"
    ansible.builtin.fail:
      msg: "Only Debian-derivatives are supported as control planes"
    when: "(ansible_os_family != 'Debian') and (role == 'control-plane')"
  - name: "Checking whether the host runs an Operating System supported for nodes"
    ansible.builtin.fail:
      msg: "Only Debian-derivatives and Red Hat-derivatives are supported as nodes"
    when: "(ansible_os_family not in ['Debian', 'RedHat']) and (role == 'node')"
  - name: "hide_on_ok: Checking if the host is a Kubernetes control plane"  # noqa fqcn-builtins
    shell: |
      lsof -i -P -n | grep 6443.*LISTEN > /dev/null
    register: "port_check_control_plane"
    failed_when: false
    changed_when: false
  - name: "hide_on_ok: Checking if the host is a Kubernetes node"  # noqa fqcn-builtins
    shell: |
      lsof -i -P -n | grep 10250.*LISTEN > /dev/null
    register: "port_check_node"
    failed_when: false
    changed_when: false
  - name: "Check whether the host is a Kubernetes control plane"
    ansible.builtin.fail:
      msg: "This host appears to already be a Kubernetes control plane"
    when: "port_check_control_plane.rc == 0"
  - name: "Check whether the host is a Kubernetes node"
    ansible.builtin.fail:
      msg: "This host appears to already be a Kubernetes node"
    when: "port_check_node.rc == 0"
