---
# yamllint disable rule:line-length
- name: "Prepare control plane"
  hosts: "selection:&controlplane:!nas:!nodes"
  vars:
    metadata:
      description: "Prepare control plane"
      summary:
        "Modified files":
          - description: "/etc/fstab (mounting of swapfiles and swap partitions disabled)"
        "Modified systemd units":
          - description: "All swap-type units masked"
        "Other actions":
          - description: "Unmounts all swap partitions"
      playbook_types:
        - "internal"
      category: "Setup"
  gather_subset:
    - "!min"
    - "!all"
    - "distribution"
  become: true
  become_user: "root"
  tasks:
    - name: "Disabling swap"  # noqa risky-shell-pipe
      ansible.builtin.shell: |
        # Disable swap entries in /etc/fstab
        sed -i -e 's,^/swapfile.*,#&,;s,^/swap.img.*,#&,;s,^UUID=[a-f0-9]*-[a-f0-9]*-[a-f0-9]*-[a-f0-9]*-[a-f0-9]* *none *swap.*,#&,' /etc/fstab
        # Disable swap units; due to systemctl -o json-pretty not working in RHEL8 we have to do this instead:
        # (we try several ways of escaping to handle corner cases; it seems different versions of systemd might
        #  be behaving differently; masking multiple times will not hurt).
        swapunits="$(systemctl --type swap | grep -i 'swap' | sed -e 's/^..\([^ ]*\).*$/\1/')"
        if [ $(systemctl --type swap | grep -c "0 loaded units listed") -eq 0 ]; then
          for swap in ${swapunits}; do
            systemctl mask "$(printf -- "${swap}")";
            systemctl mask "${swap}";
          done;
        fi
        # Disable swap during this boot
        swapoff -a
      changed_when: true
    - name: "Setting SELinux to permissive mode"
      become: true
      become_user: "root"
      ansible.builtin.shell: |
        setenforce 0
        sed -i -e 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
      when: "ansible_os_family == 'RedHat'"
      changed_when: true
