- hosts: "selection:&controlplane:!nas:!nodes"
  vars:
    metadata:
      description: "Prepare control plane"
      playbook_types:
      - "internal"
  gather_subset:
  - "!min"
  - "!all"
  - "distribution"
  become: true
  become_user: "root"
  tasks:
  - name: "Disabling swap"  # noqa fqcn-builtins risky-shell-pipe
    shell: |
      # Disable swap during this boot
      swapoff -a
      # Disable swap entries in /etc/fstab
      sed -i -e 's,^/swapfile,#&,;s,^/swap.img,#&,;s,^UUID=[a-f0-9]*-[a-f0-9]*-[a-f0-9]*-[a-f0-9]*-[a-f0-9]* *none *swap.*,#&,' /etc/fstab
      # Disable swap units
      swapunits="$(systemctl --type swap -o json-pretty)"
      if [ $(echo "${swapunits}" | grep -c "0 loaded units listed") -eq 0 ]; then
        for swap in $(systemctl --type swap -o json-pretty | grep "unit" | sed -e 's/.*"unit" : "//;s/",$//'); do
          systemctl mask "${swap}"
        done
      fi
    changed_when: false
