- hosts: controlplane:!nas:!nodes
  vars:
    metadata:
      description: Prepare control plane
      playbook-types:
      - internal
  gather_facts: no
  become: True
  become_user: root
  tasks:
  - name: Configuring Docker daemon
    template:
      dest: /etc/docker/daemon.json
      src: templates/etc/docker/daemon.json.j2
      mode: "u=rw,g=r,o=r"
      force: yes
  - name: Creating /etc/systemd/system/docker.service.d
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
      mode: "u=rwx,g=rx,o=rx"
  - name: Configuring docker/http-proxy.conf
    template:
      dest: /etc/systemd/system/docker.service.d/http-proxy.conf
      src: templates/etc/systemd/system/docker.service.d/http-proxy.conf.j2
      mode: "u=rw,g=r,o=r"
      force: yes
  - name: Restarting Docker
    systemd:
      name: docker
      daemon_reload: yes
      state: restarted
  - name: Disabling swap
    shell: |
      # Disable swap during this boot
      swapoff -a
      # Disable swap entries in /etc/fstab
      sed -i -e 's,^/swapfile,#&,;s,^/swap.img,#&,;s,^UUID=[a-f0-9]*-[a-f0-9]*-[a-f0-9]*-[a-f0-9]*-[a-f0-9]* *none *swap.*,#&,' /etc/fstab
      # Disable swap units
      swapunits="$(sudo systemctl --type swap -o json-pretty)"
      if [ $(echo "${swapunits}" | grep -c "0 loaded units listed") -eq 0 ]; then
        for swap in $(sudo systemctl --type swap -o json-pretty | grep "unit" | sed -e 's/.*"unit" : "//;s/",$//'); do
          systemctl mask "${swap}"
        done
      fi
