- hosts: "selection:!nas"
  name: "Prepare node"
  vars:
    metadata:
      description: "Prepare node"
      summary:
        "Modified files":
          - description: "/etc/fstab (mounting of swapfiles and swap partitions disabled)"
          - description: "/etc/selinux/config (SELinux set to permissive mode)"
            conditions: "Red Hat and derivatives"
        "Modified systemd units":
          - description: "All swap-type units masked"
        "Other actions":
          - description: "Unmounts all swap partitions"
      playbook_types:
        - "internal"
      category: "Setup"
  gather_subset:
    - "!min"
    - "!all"
    - "distribution"
  become: true
  become_user: "root"
  tasks:
    - name: "Disabling swap"  # noqa risky-shell-pipe
      ansible.builtin.shell: |
        # Disable swap entries in /etc/fstab
        sed -i -e 's,^/swapfile.*,#&,;s,^/swap.img.*,#&,;s,^UUID=[a-f0-9]*-[a-f0-9]*-[a-f0-9]*-[a-f0-9]*-[a-f0-9]* *none *swap.*,#&,' /etc/fstab
        # Disable swap units
        swapunits="$(systemctl --type swap -o json-pretty)"
        if [ $(systemctl --type swap | grep -c "0 loaded units listed") -eq 0 ]; then
          for swap in $(echo "${swapunits}" | grep "unit" | sed -e 's/.*"unit" : "//;s/",$//'); do
            systemctl mask "$(printf -- "${swap}")"
          done
        fi
        # Disable swap during this boot
        swapoff -a
      changed_when: true
    - name: "Setting SELinux to permissive mode"
      become: true
      become_user: "root"
      ansible.builtin.shell: |
        setenforce 0
        sed -i -e 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
      when: "ansible_os_family == 'RedHat'"
      changed_when: true
