- hosts: "selection"
  name: "Prepare the host for using Ansible without a password"
  vars:
    metadata:
      description: "Prepare the host for using Ansible without a password"
      summary:
        "Modified files":
        - description: "/etc/sudoers.d/{{ ansible_user }} (ansible_user modified to run sudo passwordless)"
        - description: "/home/{{ ansible_user }}/.ssh/authorized_keys (.ssh keys for control plane added)"
      playbook_types:
      - "internal"
      category: "Setup"
  gather_subset:
  - "!min"
  - "!all"
  - "distribution"
  become: true
  become_user: "root"
  tasks:
  - name: "Adding {{ ansible_user }} to sudoers"  # noqa name[template]
    ansible.builtin.lineinfile:
      path: "/etc/sudoers.d/{{ ansible_user }}"
      regex: "^{{ ansible_user }}"
      line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
      state: "present"
      mode: "0660"
      create: true
      validate: "visudo -cf %s"
  - name: "Adding public keys to authorized_keys"
    become: true
    become_user: "root"
    ansible.posix.authorized_key:
      user: "{{ ansible_user }}"
      state: "present"
      key: "{{ item }}"
    loop: "{{ authorized_keys }}"
