- hosts: "selection:!nas:!nodes"
  name: "Prepare node"
  vars:
    metadata:
      description: "Prepare node"
      summary:
        "Modified files":
        - description: "/etc/fstab (swap disabled)"
        - description: "/etc/selinux/config (SELinux set to permissive mode)"
          conditions: "Red Hat and derivatives"
        "Modified systemd units":
        - description: "All swap-type units masked"
      playbook_types:
      - "internal"
      category: "Setup"
  gather_subset:
  - "!min"
  - "!all"
  - "distribution"
  become: true
  become_user: "root"
  tasks:
  - name: "Disabling swap"  # noqa fqcn-builtins risky-shell-pipe
    shell: |
      # Disable swap during this boot
      swapoff -a
      # Disable swap entries in /etc/fstab
      sed -i -e 's,^/swapfile,#&,;s,^/swap.img,#&,;s,^UUID=[a-f0-9]*-[a-f0-9]*-[a-f0-9]*-[a-f0-9]*-[a-f0-9]* *none *swap.*,#&,' /etc/fstab
      # Disable swap units
      swapunits="$(systemctl --type swap -o json-pretty)"
      if [ $(echo "${swapunits}" | grep -c "0 loaded units listed") -eq 0 ]; then
        for swap in $(systemctl --type swap -o json-pretty | grep "unit" | sed -e 's/.*"unit" : "//;s/",$//'); do
          systemctl mask "$(printf -- "${swap}")"
        done
      fi
    changed_when: false
  - name: "Setting SELinux to permissive mode"  # noqa fqcn-builtins
    become: true
    become_user: "root"
    shell: |
      setenforce 0
      sed -i -e 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
    when: "ansible_os_family == 'RedHat'"
