- hosts: selection:!controlplane:!nas
  vars:
    metadata:
      description: "Reboot"
      confirm: true
      allow_on_control_plane: "never"
      category: "Administration"
  gather_facts: false
  become: true
  become_user: "root"
  tasks:
  - name: "Rebooting system"
    ansible.builtin.reboot:
