- hosts: "selection:!controlplane:!nas:!localhost"
  name: "Reboot"
  vars:
    metadata:
      description: "Reboot"
      summary:
        "System actions":
        - description: "Reboots the system"
      playbook_types:
      - "cmtinv"
      - "inventory"
      - "nodes"
      confirm: true
      allow_on_control_plane: "never"
      category: "Administration"
  gather_facts: false
  become: true
  become_user: "root"
  tasks:
  - name: "Rebooting system"
    ansible.builtin.reboot:
