- hosts: selection:!controlplane:!nas
  vars:
    metadata:
      description: Reboot
      confirm: True
      allow-on-control-plane: never
      category: Administration
  gather_facts: no
  become: True
  become_user: root
  tasks:
  - name: Reboot system
    reboot:
