- hosts: "selection:!controlplane:!nas"
  name: "Reboot"
  vars:
    metadata:
      description: "Reboot"
      summary:
        "System actions":
        - description: "Reboots the system"
      confirm: true
      allow_on_control_plane: "never"
      category: "Administration"
  gather_facts: false
  become: true
  become_user: "root"
  tasks:
  - name: "Rebooting system"
    ansible.builtin.reboot:
