- hosts: selection
  vars:
    metadata:
      description: Tear down container network interfaces (CNI)
      playbook-types:
      - internal
      category: Administration
  gather_facts: false
  become: true
  become_user: root
  tasks:
  - name: Tearing down container network interfaces
    shell: |
      for network in $(cat /proc/net/dev | grep -E "^antrea|^genev" | cut -f 1 -d:); do
        ifconfig "${network}" down || ip link set dev "${network}" down || true
      done
      for network in $(cat /proc/net/dev | grep -E "^cali|^tunl0:" | cut -f 1 -d:); do
        ifconfig "${network}" down || ip link set dev "${network}" down || true
      done
      for network in $(cat /proc/net/dev | grep -E "^cilium|^lxc" | cut -f 1 -d:); do
        ifconfig "${network}" down || ip link set dev "${network}" down || true
      done
      for network in $(cat /proc/net/dev | grep -E "^flannel|^cni0" | cut -f 1 -d:); do
        ifconfig "${network}" down || ip link set dev "${network}" down || true
      done
      for network in $(cat /proc/net/dev | grep -E "^veth" | cut -f 1 -d:); do
        ifconfig "${network}" down || ip link set dev "${network}" down || true
      done
      for network in $(cat /proc/net/dev | grep -E "^kube-bridge" | cut -f 1 -d:); do
        ifconfig "${network}" down || ip link set dev "${network}" down || true
      done
      for network in $(cat /proc/net/dev | grep -E "^datapath|^vxlan|^weave" | cut -f 1 -d:); do
        ifconfig "${network}" down || ip link set dev "${network}" down || true
      done
      killall -q weaver || true
  - name: Removing leftover network configurations
    shell: |
      rm -rf /etc/cni /opt/cni /var/lib/cni /var/lib/weave
      iptables -F
      iptables -t nat -F
      iptables -t mangle -F
      iptables -X
