---
# yamllint disable rule:line-length
- name: "Tear down container network interfaces (CNI)"
  hosts: "selection"
  vars:
    metadata:
      description: "Tear down container network interfaces (CNI)"
      summary:
        "Deleted directories":
          - description: "/etc/cni"
          - description: "/etc/origin/openvswitch"
          - description: "/etc/origin/ovn"
          - description: "/var/lib/cni"
          - description: "/var/lib/weave"
          - description: "/var/log/openvswitch"
          - description: "/var/log/ovn"
          - description: "/var/run/openvswitch"
          - description: "/var/run/ovn"
        "Deleted files":
          - description: "/etc/cni/*"
          - description: "/etc/origin/openvswitch/*"
          - description: "/etc/origin/ovn/*"
          - description: "/var/lib/cni/*"
          - description: "/var/lib/weave/*"
          - description: "/var/log/openvswitch/*"
          - description: "/var/log/ovn/*"
          - description: "/var/run/openvswitch/*"
          - description: "/var/run/ovn/*"
        "Other actions":
          - description: "Deletes all CNI-related network interfaces"
          - description: "Kills the weaver process"
          - description: "Deletes iptable rules"
      playbook_types:
        - "internal"
      category: "Administration"
  gather_facts: false
  become: true
  become_user: "root"
  tasks:
    - name: "Tearing down container network interfaces"
      ansible.builtin.shell:
        executable: "/bin/bash"
        cmd: |
          set -o pipefail
          if [ -x /usr/sbin/ip ]; then
            for network in $(cat /proc/net/dev | grep -E "^antrea|^genev" | cut -f 1 -d:); do
              ip link set dev "${network}" down || true
              ip link delete "${network}" || true
            done
            for network in $(cat /proc/net/dev | grep -E "^cali|^tunl0:" | cut -f 1 -d:); do
              ip link set dev "${network}" down || true
              ip link delete "${network}" || true
            done
            for network in $(cat /proc/net/dev | grep -E "^cilium|^lxc" | cut -f 1 -d:); do
              ip link set dev "${network}" down || true
              ip link delete "${network}" || true
            done
            for network in $(cat /proc/net/dev | grep -E "^flannel|^cni0" | cut -f 1 -d:); do
              ip link set dev "${network}" down || true
              ip link delete "${network}" || true
            done
            for network in $(cat /proc/net/dev | grep -E "^veth" | cut -f 1 -d:); do
              ip link set dev "${network}" down || true
              ip link delete "${network}" || true
            done
            for network in $(cat /proc/net/dev | grep -E "^kube-bridge" | cut -f 1 -d:); do
              ip link set dev "${network}" down || true
              ip link delete "${network}" || true
            done
            for network in $(cat /proc/net/dev | grep -E "^datapath|^vxlan|^\s*weave" | cut -f 1 -d:); do
              ip link set dev "${network}" down || true
              ip link delete "${network}" || true
            done
          else
            for network in $(cat /proc/net/dev | grep -E "^antrea|^genev" | cut -f 1 -d:); do
              ifconfig "${network}" down || true
            done
            for network in $(cat /proc/net/dev | grep -E "^cali|^tunl0:" | cut -f 1 -d:); do
              ifconfig "${network}" down || true
            done
            for network in $(cat /proc/net/dev | grep -E "^cilium|^lxc" | cut -f 1 -d:); do
              ifconfig "${network}" down || true
            done
            for network in $(cat /proc/net/dev | grep -E "^flannel|^cni0" | cut -f 1 -d:); do
              ifconfig "${network}" down || true
            done
            for network in $(cat /proc/net/dev | grep -E "^veth" | cut -f 1 -d:); do
              ifconfig "${network}" down || true
            done
            for network in $(cat /proc/net/dev | grep -E "^kube-bridge" | cut -f 1 -d:); do
              ifconfig "${network}" down || true
            done
            for network in $(cat /proc/net/dev | grep -E "^datapath|^vxlan|^\s*weave" | cut -f 1 -d:); do
              ifconfig "${network}" down || true
            done
          fi
          killall -q weaver || true
      changed_when: false
    - name: "Removing leftover network configuration and binaries"
      ansible.builtin.shell:
        executable: "/bin/bash"
        cmd: |
          set -o pipefail
          rm -rf /etc/cni/* /var/lib/cni /var/lib/weave
          rm -rf /opt/cni/bin/antrea
          rm -rf /opt/cni/bin/calico
          rm -rf /opt/cni/bin/calico-ipam
          rm -rf /opt/cni/bin/cilium-cni
          rm -rf /opt/cni/bin/flannel
          rm -rf /opt/cni/bin/weave
          iptables -F
          iptables -t nat -F
          iptables -t mangle -F
          iptables -X
      changed_when: false
