- hosts: "selection:!nas"
  name: "Update the Operating System"
  vars:
    metadata:
      description: "Update the Operating System"
      summary:
        "Upgraded packages":
        - description: "All packages that can be upgraded"
      confirm: true
      allow_on_control_plane: "single"
      category: "Administration"
  gather_subset:
  - "!min"
  - "!all"
  - "distribution"
  become: true
  become_user: "root"
  tasks:
  - name: "Upgrading all packages"
    ansible.builtin.apt:
      update_cache: true
      force_apt_get: true
      upgrade: "safe"
    when: "ansible_os_family == 'Debian'"
  - name: "Upgrading all packages"  # noqa package-latest
    ansible.builtin.dnf:
      update_cache: true
      name: "*"
      state: "latest"
    when: "ansible_os_family == 'RedHat'"
  - name: "Upgrading all packages"  # noqa package-latest
    shell: |
      zypper refresh
      zypper -n update -y
    when: "ansible_os_family == 'Suse'"
