- hosts: selection:!nas
  vars:
    metadata:
      description: Update the Operating System
      confirm: true
      allow_on_control_plane: single
      category: Administration
  gather_subset:
  - '!min'
  - '!all'
  - distribution
  become: true
  become_user: root
  tasks:
  - name: Updating APT cache
    apt: update_cache=yes force_apt_get=yes
    when: ansible_os_family == 'Debian'
  - name: Upgrading all packages
    apt: upgrade=safe force_apt_get=yes
    when: ansible_os_family == 'Debian'
