- hosts: "selection"
  name: "Uptime"
  vars:
    metadata:
      description: "Uptime"
      summary:
        "Other actions":
        - description: "Executes /usr/bin/uptime"
      category: "Information"
      read_only: true
  gather_facts: false
  tasks:
  - name: "Checking uptime"  # noqa fqcn-builtins
    command: "/usr/bin/uptime"
    changed_when: false
