- hosts: selection
  vars:
    metadata:
      description: Uptime
      category: Information
  gather_facts: false
  tasks:
  - name: Check uptime
    command: /usr/bin/uptime
    changed_when: false
