- name: "Uptime"
  hosts: "selection"
  vars:
    metadata:
      description: "Uptime"
      summary:
        "Other actions":
          - description: "Executes /usr/bin/uptime"
      playbook_types:
        - "cmtinv"
        - "inventory"
        - "nodes"
      category: "Information"
      read_only: true
  gather_facts: false
  tasks:
    - name: "Checking uptime"
      ansible.builtin.command: "/usr/bin/uptime"
      changed_when: false
