- hosts: "selection"
  vars:
    metadata:
      description: "Uptime"
      category: "Information"
      read_only: true
  gather_facts: false
  tasks:
  - name: "Checking uptime"  # noqa fqcn-builtins
    command: "/usr/bin/uptime"
    changed_when: false
