- hosts: "selection"
  name: "Delete Virtual Machines"
  vars:
    metadata:
      description: "Delete Virtual Machines"
      playbook_types:
        - "internal"
      category: "Setup"
      summary:
        "Other actions":
          - description: "Destroys VM instances"
          - description: "Undefines VM instances"
  gather_subset:
  - "!min"
  - "!all"
  - "user_dir"
  tasks:
    - name: "Shutdown the VM instances"
      ansible.builtin.shell: |
        virsh --connect qemu:///system shutdown {{ item.0 }}
      loop: "{{ instances }}"
    - name: "Wait for the VM instance shutdowns to complete and undefine the VM instances"
      ansible.builtin.shell: |
        # Wait for shutdown to complete
        until virsh --connect qemu:///system domstate {{ item.0 }} | grep shut; do
            sleep 1
        done
        virsh --connect qemu:///system undefine {{ item.0 }}
      loop: "{{ instances }}"
