- hosts: "selection"
  name: "Commit VM template changes to the base image"
  vars:
    metadata:
      description: "Commit VM template changes to the base image"
      time_consumption: "Potentially slow"
      playbook_types:
        - "internal"
      category: "Setup"
      summary:
        "Modified files":
          - description: "/var/lib/libvirt/images/{{ base_image_name }}"
  gather_subset:
  - "!min"
  - "!all"
  - "user_dir"
  tasks:
    - name: "Commit changes from template image to the base image"
      ansible.builtin.shell: |
        qemu-img commit /var/lib/libvirt/images/{{ template_name }}.qcow2
      become: true
      become_user: "root"
