---
- name: "Undefine Virtual Machines"
  hosts: "selection"
  vars:
    metadata:
      description: "Undefine Virtual Machines"
      playbook_types:
        - "internal"
      category: "Setup"
  gather_subset:
    - "!min"
    - "!all"
    - "user_dir"
  tasks:
    - name: "Undefine VMs"
      ansible.builtin.shell: |
        virsh --connect qemu:///system undefine {{ item.0 }}
      loop: "{{ instances }}"
      changed_when: true
